import type { Report } from "../types"

const report: Report = {
  slug: "origin-and-callbacks",
  order: 2,
  title: "Names, origin and callbacks in Dutch hiring",
  subtitle: "What field experiments with matched CVs show, and how odds uses them without overstating them.",
  category: "Odds",
  minutes: 31,
  headline: { figure: "0.76", line: "callbacks for a migration background against 1 for native names (35% against 46%). odds uses 0.93 for graduate jobs" },
  feeds: "Interview chance",
  art: "scales",
  abstract: "Researchers have sent matched fictitious applications to real Dutch vacancies and counted the replies. This report reviews what those field experiments show about names, origin and callbacks, and how odds uses them. Dutch experiments between 2008 and 2019 find that applications carrying a minority signal receive fewer positive responses. The largest and most recent, with 4,211 applications, predicts 46% positive responses for native names against 35% for a migration background. The gap differs by region of origin, by occupation and, in the one study with a clean split, by function level, where it was smaller for hbo and wo jobs. No Dutch experiment tests a foreign degree. The report sets these results beside CBS register data on unemployment, participation and staying in the Netherlands, explains why the two kinds of evidence differ, and describes how odds turns ratios of response rates into multipliers (0.76 and 0.93, with 0.72 as an alternative), applies an overlap rule to the low and high bounds, and prints a range instead of a point.",
  findings: [
    "In the Dutch arm of a European correspondence test (4,211 applications, 2016 to 2018), the predicted share of positive responses was 46% for native names and 35% for a migration background, a ratio of about 0.76 [1].",
    "By region of origin the predicted share ran from 38% for Western Europe to 31% for the Middle East and North Africa, against 46% for native names [2].",
    "In the only Dutch study with a clean split by function level, the predicted invitation rate for hbo and wo jobs was 46% for natives and 43% for non-Western applicants, a 3 point gap, against 40% and 32% at the lowest level [3].",
    "CBS register data for 2025 show unemployment of 2.9% for people of Dutch origin, 5.5% for origin elsewhere in Europe and 6.6% for origin outside Europe, which describes outcomes but does not isolate the effect of a name [4].",
    "odds converts the experiments into a multiplier of 0.76 for the low bound and 0.93 for the high bound, and never multiplies the origin and foreign experience effects together in the high bound [5].",
    "No Dutch experiment isolates a foreign degree, and a 2026 field experiment on 2,100 applications in Belgium, the Netherlands and Spain found that a study-abroad period made no difference to interview invitations [6]."
  ],
  sections: [
    {
      heading: "Introduction",
      blocks: [
        { type: "p", text: "Imagine two applications for the same vacancy. They list the same degree, the same experience and the same skills, written in the same way. The only difference between them is a name. One employer replies to one of the two and not to the other. Was it chance? For a single employer there is no way to tell. For several thousand vacancies there is, and that is the idea behind the research reviewed in this report." },
        { type: "p", text: "odds estimates the chance of an interview for a given profile and a given posting. The estimate has two parts: a base rate, the share of applicants who reach an interview in some measured population, and a set of adjustments, each taken from a field experiment in which otherwise identical applications were sent to real vacancies and only one trait was changed [5]. One adjustment concerns a non-native name or origin. It is the most sensitive number in the product, because it describes how some employers reacted to a signal on a CV and is easy to read as a statement about the applicant. It is not one. It says nothing about the quality of any person, and it is an average over many employers, not a prediction of what any one employer will do." },
        { type: "p", text: "The report explains what a field experiment (also called a correspondence test) measures and leaves out, sets out each Dutch study with its design, sample, result and caveat, and looks at how the gap differs by region of origin, by occupation and by function level, which matters for graduates applying to hbo and wo level roles. It then compares the experiments with register data from Statistics Netherlands (CBS), which answer a different question, and shows how odds derives the multipliers 0.76 and 0.93 (with 0.72 as an alternative) and what the printed range does and does not claim." },
        { type: "p", text: "Two cautions run through everything that follows. First, the evidence is about the first reaction of an employer to a written or database signal. It is not about offers or treatment at work. Second, most of the Dutch experiments used fictitious candidates with Dutch education and a Dutch-language CV. An international graduate differs in more than a name: a degree from elsewhere, possibly a work permit question, a different language background. Nothing here is legal, tax or immigration advice. Questions about rights should go to official government sources, for example rijksoverheid.nl." },
      ]
    },
    {
      heading: "Data and sources",
      blocks: [
        { type: "p", text: "Three kinds of source are used: the published Dutch field experiments on hiring discrimination, read from the reports and articles themselves; CBS StatLine, the open data service of Statistics Netherlands, which publishes register-based tables on employment and higher education leavers; and a small set of benchmarks from outside the Netherlands and from software vendors, used for the base rate and two other adjustments. Each is labelled as such where it is used." },
        { type: "h3", text: "The Dutch experiments" },
        { type: "p", text: "{ref:tbl-studies} lists the Dutch studies that report origin gaps and that odds collected. They are not one series: years (2008 to 2019), groups, job levels and kinds of first contact, from a written application to a phone call to a recruiter viewing a CV in a database, all differ. Where a figure is reported in a secondary source rather than the primary report, the text says so. For the 2015 Panteia test, for example, the headline shares were read from the 2019 repeat report, and the group-by-group ratios, which appear only in a review article, were not checked against the primary source and are not used by odds [7, 2]." },
        { type: "table", id: "tbl-studies", caption: "Dutch field studies of hiring and origin used in this report.", head: ["Study", "Data collected", "Design and sample", "Headline result"], rows: [
          ["SCP, Liever Mark dan Mohammed? (2010)", "May to December 2008", "Written and telephone tests; 1,409 tests, 1,342 valid; Turkish, Moroccan, Surinamese and Antillean applicants", "Invited to interview: 44% native, 37% non-Western"],
          ["SCP, Op achterstand (2012)", "April to December 2011", "Temp agencies: 460 valid walk-in visits by 20 actors; 263 online applications", "Walk-in job offer: 46% native, 28% non-Western; online interest 34% for all groups"],
          ["Blommaert, Coenders and van Tubergen (2014)", "2011", "636 fictitious CVs on two online CV databases; Dutch-named against Arabic-named", "Positive reactions per CV: 0.76 against 0.47"],
          ["Panteia for SZW (2015)", "2015", "1,742 fictitious CVs on online CV databases (1,346 in the origin analysis); mbo-level profiles", "Email or voicemail: 29% against 12%"],
          ["Panteia for SZW (2019)", "2018 to 2019", "707 CVs placed, 638 analysed; six mbo occupations", "Any contact: 64% against 58%"],
          ["GEMM Netherlands (Thijssen et al. 2019, 2021)", "July 2016 to 2018", "4,211 applications; ten occupations at mbo and hbo level; 35 origin groups", "Predicted positive response: 46% native, 35% migration background"],
          ["Inspectie SZW pilot (2019)", "2019", "Mystery calls to temp agencies with a discriminatory client request (not a CV test)", "Complied: 40% of non-affiliated agencies, 13% of ABU members, 26% of NBBU members"]
        ], note: "Shares are as reported by each study; designs and outcome definitions differ, so rows are not directly comparable. Sources: [3, 8, 9, 10, 7, 2, 1, 11]." },
        { type: "p", text: "The 2021 cross-national overview of the same European project counts 4,463 Dutch applications, slightly more than the 4,211 in the Dutch article, and labels the occupations somewhat differently [12, 2]. The overall share of positive responses in the Dutch article is 38% (1,587 of 4,211), while a share that odds computed from a table of the overview comes to about 46%; the definitions behind the two were not reconciled. This is a reason to be cautious about absolute levels, and it is why the derivation here uses only rates taken from the same study and model." },
        { type: "h3", text: "Register data" },
        { type: "p", text: "The register evidence comes from CBS StatLine tables retrieved on 29 September 2026 under the CBS open licence. Table 85456NED gives participation and unemployment by origin for all education levels, with no education level but a startkwalificatie (basic qualification) dimension [4]. Table 84729NED gives net participation by detailed country of origin and education level, including hbo and wo, for 2021 to 2024, but no unemployment rate [13]. Table 85776NED follows higher education leavers from 2006/07 to 2023/24 by origin and by whether they were an international student [14]. Table 85266NED gives the baseline for all origins [15]. StatLine has no table that crosses education level with origin and the unemployment rate, and none that gives job search duration by origin [16]." },
        { type: "h3", text: "Benchmarks used for context" },
        { type: "p", text: "The base rate used in odds comes from two software vendors, not from the Dutch experiments. Ashby reports 170 applications per hire for business roles in EMEA scale-ups (180,000 jobs) and an offer acceptance rate of 81% across 54 million applications [17]. SmartRecruiters reports, across 89 million applications in 95 countries, 3.9% of applicants interviewed and 1.2% offered, and 5.4% interviewed in Germany [18]. Two further adjustments are not Dutch: an audit study of more than 8,000 fictitious resumes on work experience gained outside the local market [19] and a US vendor test of tailored cover letters on 7,287 applications [20]. Dutch labour market tightness comes from the UWV employer survey of 3,551 employers [21]. A search in Dutch and English, covering 2010 to 2026, found no Dutch correspondence test that isolates a foreign degree or foreign work experience [22]." },
      ]
    },
    {
      heading: "What a correspondence test measures",
      blocks: [
        { type: "p", text: "A field experiment on hiring, also called a correspondence test, is one of the few ways to measure how employers react to a single trait, because everything else is held equal by design. Researchers create fictitious candidates and send their applications to real vacancies. Each vacancy receives a matched set that differs only in the trait under study, for example a Dutch-sounding name against a name associated with another origin. Then the researchers count the positive responses each version receives. Because the vacancy, the employer, the week and the content of the application are the same, a consistent difference in the counts can be attributed to the trait that was varied." },
        { type: "p", text: "A percentage point is the difference between two percentages: 46% against 35% is 11 percentage points. A ratio divides one rate by the other: 35 divided by 46 is 0.76, meaning that applications with the minority signal received about three quarters as many positive responses, or about 24% fewer. The two measures answer different questions. A difference of 11 points looks the same whether the native rate is 46% or 80%, while a ratio of 0.76 keeps its meaning when applied to a different base rate. This is why odds uses ratios: the ratio can be carried onto a base rate of a few percent, and the point difference cannot." },
        { type: "p", text: "Many figures in this report are described as predicted. A predicted rate is the output of a statistical model corrected for other characteristics in the data: in the SCP study, for sex, age, experience and sector [3]; in the Dutch arm of the European test, by origin group [2]. Predicted rates remove differences in the mix of vacancies that happened to be tested, but they remain estimates with a margin of error. The sources give statements of statistical significance (a difference unlikely to be due to chance at the usual threshold) but, for most figures, not the confidence intervals, and this report does not invent them." },
        { type: "art", id: "fig-scales", kind: "scales", caption: "Two otherwise identical applications are weighed against each other, and the small tilt across thousands of vacancies is the result; the drawing stands for the difference in positive response rates, not for any single employer." },
        { type: "p", text: "{ref:fig-scales} puts the idea in a picture. The strength of the method is that the comparison is fair. The weakness is that it measures one narrow thing. It captures the reaction at the first step, usually to an application on paper or a CV in a database, and not what happens afterwards in an interview or on the job. It measures an average over many employers, not what any given employer will do, and it measures a signal, a name, which is not the same as a person." },
        { type: "p", text: "Take the headline of the Dutch arm of the European test, 46% against 35% [1]. Suppose, as an illustration only, that 1,000 vacancies each received one application of each kind: about 460 would be answered positively for the native-named application and about 350 for the other, a gap of 11 points and a ratio of 0.76. The SCP result for hbo and wo jobs, 46% against 43%, would give about 460 against 430, a gap of 3 points and a ratio of 0.93 [3]. The two imply quite different penalties, and much of this report is about why, and which to apply to an international graduate." },
      ]
    },
    {
      heading: "The Dutch experiments, 2008 to 2019",
      blocks: [
        { type: "p", text: "The Dutch literature begins, for the purposes of this report, with a study by the research institute SCP and runs to the large European project that reports in 2019 and 2021. Each study is summarised below with its design, its sample and what it does not show." },
        { type: "h3", text: "SCP 2010: Liever Mark dan Mohammed?" },
        { type: "p", text: "The SCP study ran 1,409 tests between May and December 2008, of which 1,342 were valid, by written application and by telephone, for Turkish, Moroccan, Surinamese and Antillean applicants in five sectors: healthcare, financial services, hospitality, municipalities and retail [3]. Overall, 44% of native applicants were invited to an interview, against 37% of non-Western applicants: a gap of 7 percentage points, or 16% fewer invitations (37 divided by 44 is 0.84). Matched on the same vacancies, the gap was a little over 5 points for Moroccan, about 8 for Surinamese and about 7 for Turkish and Antillean applicants. In jobs with customer contact the gap was 9 points, against 5 points in jobs without. By sector, the native and non-Western rates were 55% and 49% in financial services, 57% and 51% in healthcare, 50% and 39% in hospitality, 36% and 33% in municipalities and 31% and 21% in retail. The study found no difference between starters and experienced applicants." },
        { type: "h3", text: "The 2012 follow-up at temp agencies" },
        { type: "p", text: "A second SCP report ran in-person tests at temporary employment agencies in the Randstad in 2011: 460 valid visits by 20 actors and 263 online applications [8]. The chance of a job offer after a walk-in was 46% for natives against 28% for non-Western applicants, a ratio of 1.6 in the report's own terms. It was 33% for non-Western women and 23% for men. Moroccan applicants had chances equal to natives, while Turkish, Surinamese and Antillean applicants did worse. Online, however, the first-stage interest was 34% for all groups, with no difference by origin or sex. The jobs were predominantly lower and mid-level: the report notes that only 18% of temp workers are highly educated, so the study cannot speak to graduate roles. How a signal is delivered can change how it is read." },
        { type: "h3", text: "Blommaert and colleagues 2014: CV databases" },
        { type: "p", text: "This study looked at employers searching an online CV database. The authors placed 636 fictitious CVs on two databases in 2011 at mbo, hbo and wo levels across five sectors and ten regions. Dutch-named CVs were viewed in full 9.57 times on average, against 6.36 for Arabic-named CVs, about 50% more. Positive reactions were 0.76 against 0.47 per CV, about 60% more, and 64% of the 72 CVs never viewed were Arabic-named [9]. The pattern in views held regardless of education, gender, age, region or sector. The study compares Dutch names with Arabic (Moroccan) names only, and gives no separate point estimates for hbo and wo in the text odds holds." },
        { type: "h3", text: "Panteia for SZW, 2015 and 2019" },
        { type: "p", text: "Two virtual tests of online CV databases, commissioned by the Ministry of Social Affairs and Employment (SZW), used mbo-level profiles only. In 2015, with 1,742 fictitious CVs, the chance of an email or voicemail was 29% with no migration background against 12% with one, and the chance of a phone call was 27% against 17% [10, 7]. In the repeat of 2018 to 2019, with 638 analysed CVs out of 707 placed, six mbo occupations and the same groups, any interaction was 64% against 58%, a significant but smaller gap. By channel, an email or voicemail was 35% against 27% and a phone call 31% against 29%. The report states that the gap narrowed compared with 2015 [7]. On one or more approaches, Dutch CVs reached 35%, Moroccan CVs 23% and Turkish CVs 24%; Antillean, Polish and Surinamese CVs were about 5 points below the control group." },
        { type: "p", text: "The change between 2015 and 2019 should be read with care. The 2019 ratio for any contact is 58 divided by 64, or 0.91. The 2015 shares are for email or voicemail and for phone calls, not for any interaction, so the years are not measured on exactly the same outcome. On email or voicemail alone the ratio was about 0.41 in 2015 (12 divided by 29) and about 0.77 in 2019 (27 divided by 35). The direction is clear; the size of the narrowing depends on the outcome chosen. Both tests were mbo only." },
        { type: "h3", text: "GEMM Netherlands, 2016 to 2018" },
        { type: "p", text: "The largest and most recent study is the Dutch arm of a European correspondence project. It sent 4,211 applications across ten occupations (cook, electrician, plumber, carpenter, receptionist, sales assistant, hairdresser, administrative clerk, software developer and account manager), at mbo and hbo level, for 35 origin groups [2]. Overall, 38% of applications received a positive response (1,587 of 4,211). The predicted share was 46% for native names and 35% for a migration background, which splits into 38% for Western and 33% for non-Western minorities [1]. The cross-national overview reports a gap of 14 percentage points for Moroccan applicants in the Netherlands against 6 in Spain, and 15 points for Turkish applicants against 5 in Germany [12]. The authors' discrimination ratios (native rate divided by minority rate) are 1.2 for Western minorities, 1.4 for non-Western, 1.5 for Moroccan, 1.4 for Turkish and 1.3 for Bulgarian applicants; these are the inverse of the multipliers used here (1 divided by 1.4 is about 0.72) [2]." },
        { type: "p", text: "The same study reports the share of positive responses across all applicants by occupation: cook 58%, software developer 54%, hairdresser 49%, plumber 47%, carpenter 46%, electrician 45%, account manager 27%, sales assistant 24%, receptionist 23% and administrative clerk 18% [2]. These levels are far above the 2.4% to 5.4% base rate described later, as expected: the experiment applications were written to fit the vacancy, while the base rate describes all applicants to all postings. odds prints the occupation rates as a separate line and never multiplies them into the estimate [5]." },
        { type: "p", text: "The Dutch experiments agree in direction. According to the notes compiled by odds, all of them since 2008 find a penalty for a non-Western name of roughly 15% to 40% in relative terms, and two of them (SCP 2010 and Panteia 2019) indicate that it is smaller when labour demand is tight and larger in customer-facing roles [22]. They disagree about its size, which depends on the design, the year, the job level and the group, and they cannot be lined up as a single series." }
      ]
    },
    {
      heading: "Region of origin, function level and occupation",
      blocks: [
        { type: "p", text: "The headline ratio of 0.76 pools a wide range of origins. {ref:fig-region} shows the model-predicted shares of positive responses in the Dutch arm of the European test by region of origin. The gap to native names is smallest for applicants from Western Europe and largest for those from the Middle East and North Africa [2]." },
        { type: "bars", id: "fig-region", caption: "Predicted positive response by region of origin, Netherlands, 2016 to 2018.", unit: "% of applications", items: [
          { label: "Native Dutch names", value: 46 },
          { label: "Western Europe", value: 38 },
          { label: "Eastern Europe and Russia", value: 37 },
          { label: "South-East and East Asia", value: 37 },
          { label: "Latin America", value: 33 },
          { label: "Sub-Saharan Africa", value: 32 },
          { label: "Middle East and North Africa", value: 31 }
        ], note: "Model-predicted values, GEMM Netherlands, 4,211 applications. By group: Moroccan 31%, Turkish 32%, Surinamese 36% and Polish 40%; the Polish figure was not significantly different from native. Source: [2]." },
        { type: "p", text: "Dividing each predicted rate by the native rate of 46% gives, as plain arithmetic, ratios of about 0.83 for Western Europe, 0.80 for Eastern Europe and for South-East and East Asia, 0.72 for Latin America, 0.70 for Sub-Saharan Africa and 0.67 for the Middle East and North Africa. One pooled multiplier therefore hides differences of up to 16 points of relative response between regions. odds does not use a region-specific multiplier, because the notes it holds do not give the number of applications in each region, so a regional multiplier would carry more uncertainty than the pooled one." },
        { type: "h3", text: "Function level: the one clean split" },
        { type: "p", text: "Is the gap smaller for graduate jobs? The SCP study is the only Dutch study with a clean split by function level, and {ref:tbl-level} gives its predicted invitation rates. The report states that the gap at the highest level was significantly smaller than at the lowest [3]." },
        { type: "table", id: "tbl-level", caption: "Predicted invitation rates by function level, SCP 2010.", head: ["Function level", "Native", "Non-Western", "Gap, points", "Ratio"], rows: [
          ["Low (mbo-4 or below)", "40%", "32%", "8", "0.80"],
          ["Middle", "47%", "38%", "9", "0.81"],
          ["High (hbo or wo)", "46%", "43%", "3", "0.93"]
        ], note: "Predicted rates corrected for sex, age, experience and sector; 1,342 valid tests from 2008. The ratio column is the non-Western rate divided by the native rate (odds arithmetic). Source: [3]." },
        { type: "p", text: "Read plainly, {ref:tbl-level} says that in 2008 the penalty in this study was 8 to 9 points at lower and middle levels and 3 points at hbo and wo level. The ratio for the highest level, 43 divided by 46, is 0.93. That is the figure odds uses for its high bound. What the table does not say is how precisely the 3 points are estimated: the notes hold a significance statement for the difference between levels but no confidence interval for the 3 points themselves." },
        { type: "p", text: "The other studies do not show the same shrinking. The Dutch arm of the European test finds, for the one hbo-level occupation with a relational character, account manager, no difference between how Western and non-Western minorities were treated: both were penalised equally. The same paper finds non-Western applicants penalised more than Western ones in three of four types of occupation, but the per-type ratios appear only in a chart that odds could not read numerically [2]. Blommaert and colleagues found no difference by education level in discrimination in views [9]. So one study with a clean split finds a much smaller gap at graduate level, and two others do not find the gap shrinking. The SCP data are from 2008 and the European data from 2016 to 2018, so the defensible reading is that the graduate-level gap is uncertain, not that it is gone." },
      ]
    },
    {
      heading: "Register data on unemployment, participation and staying",
      blocks: [
        { type: "p", text: "Experiments and registers answer different questions. A correspondence test isolates the effect of one signal at one step, with everything else matched. A register such as the CBS labour force statistics records what happened to whole groups of people, including everything that differs between those groups: age, education, language, the time since arrival, the region, the sector, the type of contract, and the permit. The register can show that a gap exists, but not how much of it comes from employers reacting to a name." },
        { type: "h3", text: "Unemployment and participation by origin" },
        { type: "p", text: "{ref:tbl-cbs} gives 2025 values from table 85456NED for all education levels, both sexes. The unemployment rate was 2.9% for people of Dutch origin, 5.5% for people with origin elsewhere in Europe and 6.6% for origin outside Europe. Net labour participation, the share of the population in work, was 74.5%, 72.9% and 69.0% [4]. For the four large origin countries outside Europe shown in the table, unemployment lies between 3.9% (Indonesia) and 6.9% (Turkey). The decomposition of the group with origin outside Europe is instructive: people born outside the Netherlands had a participation rate of 62.8%, while people born in the Netherlands with origin outside Europe had 76.7%, above the Dutch-origin figure of 74.5%, with unemployment of 6.7% and 6.4% respectively." },
        { type: "table", id: "tbl-cbs", caption: "Net labour participation and unemployment by origin, all education levels, 2025.", head: ["Origin group", "Net participation, %", "Unemployment, %"], rows: [
          ["Netherlands", "74.5", "2.9"],
          ["Europe excluding the Netherlands", "72.9", "5.5"],
          ["Outside Europe", "69.0", "6.6"],
          ["Outside Europe, born abroad", "62.8", "6.7"],
          ["Outside Europe, born in the Netherlands", "76.7", "6.4"],
          ["Turkey", "68.1", "6.9"],
          ["Morocco", "66.1", "6.6"],
          ["Suriname", "70.5", "6.7"],
          ["Indonesia", "65.1", "3.9"],
          ["All origins", "73.2", "3.9"]
        ], note: "Annual values, both sexes, all education levels. Source: CBS StatLine table 85456NED [4]." },
        { type: "p", text: "The unemployment gap has narrowed. For origin outside Europe, unemployment was 7.5% in 2019, 6.4% in 2022 and 6.6% in 2025, against 3.7%, 2.8% and 2.9% for Dutch origin; the difference was 7.6 points in 2013 and 3.7 points in 2025 [4]. Among people with a startkwalificatie, the closest available proxy for being qualified, the 2025 rates were 2.6% for Dutch origin, 5.2% for Europe and 5.3% for outside Europe [4]. A ratio of unemployment rates (6.6 divided by 2.9, about 2.3) is not comparable with a callback ratio of 0.76: unemployment is a stock of people without work at a moment, shaped by how long searches last, while a callback is a flow at the first stage of one application." },
        { type: "h3", text: "Participation of hbo and wo educated people by country of origin" },
        { type: "p", text: "Table 84729NED adds the education level, although without an unemployment rate. For people with an hbo or wo education in 2024, net participation was 82% overall and 83% for those of Dutch origin [13]. Among those born in the Netherlands it was 83% and among those born abroad 77%, with 26% of employed foreign-born people on a flexible contract against 17% of the Dutch-born, and 16% self-employed [13]. {ref:fig-country} shows selected countries." },
        { type: "bars", id: "fig-country", caption: "Net labour participation of people with an hbo or wo education, by country of origin, 2024.", unit: "% of the population", items: [
          { label: "Spain", value: 87 },
          { label: "Poland", value: 84 },
          { label: "India", value: 84 },
          { label: "Netherlands", value: 83 },
          { label: "Turkey", value: 81 },
          { label: "Morocco", value: 81 },
          { label: "Germany", value: 78 },
          { label: "United States", value: 76 },
          { label: "China", value: 72 },
          { label: "Ukraine", value: 64 },
          { label: "Syria", value: 56 }
        ], note: "CBS values with all parents' birth countries combined. Other values include Italy 86, Brazil 86, South Africa 88, Suriname 82, Bulgaria 83, Romania 81, Iran 77, Russia 74, Indonesia 74 and Iraq 68. Source: CBS StatLine table 84729NED [13]." },
        { type: "p", text: "The spread in {ref:fig-country} is large, from 56% to 88%, and it does not line up with the ordering in the experiments. Among hbo and wo educated people of Turkish and Moroccan origin, groups with some of the largest callback gaps, participation was 81%, two points below the Dutch figure, while for origin in Spain, India or Poland it was above it. The table does not show why. It does not separate graduates who studied in the Netherlands from those who arrived later, nor the generation, so the ordering is not a ranking of how employers treat groups." },
        { type: "h3", text: "Staying and working after graduation" },
        { type: "p", text: "The table most relevant to international graduates is 85776NED, which records the labour market position of higher education leavers one year after they leave. The latest cohort with one year of data is 2022/23. {ref:tbl-stay} reports shares of the cohort (computed by odds from CBS counts) for leavers with a wo diploma, and two hbo rows for comparison. The last column restates the work share among those still registered in the Netherlands, dividing the work share by one minus the share who left." },
        { type: "table", id: "tbl-stay", caption: "Position one year after graduating, cohort 2022/23, leavers with a diploma.", head: ["Group", "Leavers", "Working, %", "Left the Netherlands, %", "Working among those who stayed, %"], rows: [
          ["WO, origin Netherlands", "34,710", "82.1", "2.9", "85"],
          ["WO, origin elsewhere in Europe", "17,170", "32.6", "54.3", "71"],
          ["WO, origin outside Europe", "14,700", "59.5", "23.9", "78"],
          ["WO, born in the Netherlands, parent(s) from outside Europe", "5,260", "78.7", "3.4", "81"],
          ["WO, born outside Europe", "9,440", "48.9", "35.3", "76"],
          ["WO, international student", "21,400", "30.3", "56.6", "70"],
          ["WO, not an international student", "45,180", "80.5", "3.8", "84"],
          ["HBO, international student", "5,710", "33.3", "55.7", "75"],
          ["HBO, not an international student", "51,800", "89.4", "1.8", "91"]
        ], note: "Working means in work, possibly alongside a benefit. Left the Netherlands means deregistered from the population register. The last column is odds arithmetic, and it is not a causal estimate. Source: CBS StatLine table 85776NED [14]." },
        { type: "p", text: "Two findings stand out in {ref:tbl-stay}. The first concerns staying. Among international wo graduates, 56.6% had left the register one year after graduating and only 30.3% were working in the Netherlands; the five year figure for all international graduates in a separate Nuffic source is 25.3% still in the country [14, 23]. Staying is the minority outcome. The second concerns those who stay. Among international wo graduates who were still registered, about 70% were working, against about 84% of wo graduates who were not international students, a gap of 14 points. By origin group, 85% of Dutch-origin wo graduates who stayed were working, against 78% of those with origin outside Europe, 76% of those born outside Europe and 81% of those born in the Netherlands with a parent from outside Europe." },
        { type: "p", text: "These shares mix many things, and the table records none of the reasons. Conditioning on staying is also not neutral: people who left may differ from those who stayed in ways the data cannot show. The last column of {ref:tbl-stay} is therefore a description of what happened to a cohort, not a measurement of how employers treat graduates with a given origin. It is useful for one purpose: it tells an international graduate what the outcomes of earlier cohorts looked like, which no experiment does." },
      ]
    },
    {
      heading: "From ratios to the odds multipliers",
      blocks: [
        { type: "p", text: "odds needs a number that it can apply to a base rate. Every multiplier is a ratio of two rates taken from a single study [5]. {ref:tbl-mult} lists the multipliers, where they come from, and where they are used." },
        { type: "table", id: "tbl-mult", caption: "Multipliers derived from the experiments and how each is used.", head: ["Factor", "Derivation", "Value", "Where odds uses it"], rows: [
          ["Non-native background, all job levels", "35% divided by 46% (GEMM Netherlands, 4,211 applications)", "0.76", "Low bound"],
          ["Non-native background, hbo and wo level jobs", "43% divided by 46% (SCP 2010, 1,342 valid tests)", "0.93", "High bound"],
          ["Non-Western origin only (alternative)", "33% divided by 46% (GEMM Netherlands)", "0.72", "Not used; shows how the choice could move"],
          ["Western minority (midpoint for EU origin)", "38% divided by 46% (GEMM Netherlands)", "0.83", "Not used; midpoint in the research notes"],
          ["Work experience mostly outside the EU", "Audit study outside the Netherlands, more than 8,000 resumes", "0.88", "Low bound only when it overlaps with origin"],
          ["Degree obtained abroad", "Field experiment, 2,100 applications in BE, NL and ES", "1.00", "Shown so the reader knows no effect was measured"],
          ["Low bound, origin and experience", "0.76 times 0.88", "0.67", "Low bound"]
        ], note: "Rates are model-predicted shares of positive responses. Sources: [1, 3, 19, 6, 5]." },
        { type: "p", text: "The choice of 0.76 for the low bound reflects that it is the pooled estimate from the largest and most recent Dutch test. The choice of 0.93 for the high bound reflects that it is the only Dutch estimate specific to hbo and wo level. A third candidate, 0.72, arises if one takes only the non-Western group from the same test (33% divided by 46%), and the notes treat the Western minority figure (38% divided by 46%, about 0.83) as a midpoint for EU-origin applicants. The product uses 0.76 for a non-native background; the other two show how the choice could move. The effect is small in absolute terms: with a base of 2.4%, 0.76 gives 1.8% and 0.72 gives 1.7%." },
        { type: "h3", text: "The base rate and a worked example" },
        { type: "p", text: "The base is a range because the two best-known funnels disagree. Ashby implies 1 divided by 170 hires per application, or 0.59%; dividing by the offer acceptance rate of 0.81 gives 0.73% offers per application; and multiplying by 3.25 interviews per offer (3.9% interviewed divided by 1.2% offered in the SmartRecruiters data) gives about 2.4% interviews per application [17, 18]. SmartRecruiters reports 5.4% for Germany directly. The two differ by a factor of 2.3 for nominally the same question, because the definition of an interview and the customer bases differ. Neither is Dutch, and odds therefore uses the range 2.4% to 5.4% and prints both derivations [5]." },
        { type: "p", text: "{ref:fig-example} applies the origin multipliers to that range. The first line is the base. The second applies 0.76 to the low end and 0.93 to the high end. The third shows the case in which the profile also has work experience mostly outside the EU, where the low end multiplies both effects (0.76 times 0.88 is 0.67, giving 1.6%) and the high end does not. The fourth repeats the second with 0.72 at the low end." },
        { type: "ranges", id: "fig-example", caption: "Interview chance per application for a non-native profile, before other adjustments.", unit: "% per application", max: 6, items: [
          { label: "Base rate only", low: 2.4, high: 5.4 },
          { label: "Origin: 0.76 low, 0.93 high", low: 1.8, high: 5.0 },
          { label: "Origin and non-EU experience: 0.67 low, 0.93 high", low: 1.6, high: 5.0 },
          { label: "Origin, alternative: 0.72 low, 0.93 high", low: 1.7, high: 5.0 }
        ], note: "odds arithmetic on the base range of 2.4% to 5.4%, rounded to one decimal. Sources: [5, 17, 18]." },
        { type: "p", text: "The worked example published in the research notes shows the same logic with more adjustments. For a non-EU profile applying to an indirect tax accountant posting, with an internship, non-EU experience and a tailored application, the low end is 2.4% times 0.67 times 1.126, or 1.8%, and the high end is 5.4% times 0.93 times 1.126 times 1.31, or 7.4%. The displayed range is about 2% to 7%, labelled as a proxy estimate [24]. The factor 1.126 comes from a Belgian field experiment on internships and 1.31 from a US vendor test on tailored applications (12.5% to 16.4%), which enters only the high bound because vendor evidence is the weakest tier [20, 5]." },
        { type: "h3", text: "Why the low and high bounds use the evidence differently" },
        { type: "p", text: "The origin effect and the foreign experience effect plausibly measure the same thing: an employer's reaction to a profile that looks foreign. If odds multiplied both in the high bound it would count that reaction twice. The overlap rule is therefore as follows. The low bound multiplies both (0.67), accepting that this may be too pessimistic. The high bound never uses both, and takes the more favourable graduate-level origin figure (0.93) [5]. The result is a range that is open about which part is the study and which part is a choice." },
        { type: "p", text: "The evidence tier decides which bound an adjustment enters. Experimental effects from field experiments enter both bounds; vendor tests enter only the high bound; and, once odds keeps a log of real outcomes (not built yet), a cell with at least 30 entries is meant to replace the proxy base with a measured rate [5]. Coverage of the checklist, the fit of an application to a posting, is not multiplied at all, because no calibrated coefficient exists for it. The matched-CV rates from the European test, 18% to 54% in the three hbo-level occupations, sit well above the funnel rates of 2.4% to 5.4%, which is a bracket on the size of the fit effect but not a coefficient [2, 5]." },
        { type: "p", text: "The 0.88 multiplier for work experience comes from an audit study that was not run in the Netherlands and that found experience gained mostly outside the local market received about 12% fewer callbacks [19]. The Dutch evidence on foreign credentials is the 2026 field experiment, which found that a study-abroad period made no difference to the interview invitation for economics master's graduates applying to starter vacancies in Belgium, the Netherlands and Spain; it did not vary origin [6]. Applying 0.88 to non-EU experience is a choice by odds, labelled as coming from a study elsewhere." }
      ]
    },
    {
      heading: "Discussion",
      blocks: [
        { type: "p", text: "Taken together, the experiments and the registers point in the same broad direction while measuring different things. The experiments show that at the first step applications with a minority signal received fewer positive responses in every Dutch correspondence test reviewed here, with a size that depends on design, group and level. The registers show that unemployment and participation differ by origin, and more for people born abroad than for people born in the Netherlands to parents from elsewhere. The unemployment gap narrowed from 7.6 points in 2013 to 3.7 points in 2025 [4], and the Panteia repeat suggests the callback gap narrowed between 2015 and 2019 [7]. The two trends are consistent, but the data do not connect them causally." },
        { type: "p", text: "Why do the numbers differ? First, the experiments vary one signal and hold the rest constant, which no register does. Second, the experiments observe only the first reaction to a fictitious candidate, whereas the registers observe outcomes that accumulate over months. Third, register origin categories combine people with very different histories: those born abroad and those born in the Netherlands differ in participation by 6 points among hbo and wo educated people and by 14 points at all education levels. Fourth, the periods differ (2008, 2016 to 2018 and 2025)." },
        { type: "p", text: "Where do sources genuinely disagree? On the size of the penalty for a non-Western name the Dutch studies range from a ratio of about 0.41 for email or voicemail in the 2015 CV database test to about 0.93 for hbo and wo jobs in 2008 [7, 3]. They disagree on whether it shrinks at graduate level, and on the absolute level of positive responses (38% overall in the Dutch article, about 46% computed from the overview table) [2, 12]. This is why odds prints a range." },
      ]
    },
    {
      heading: "Limitations",
      blocks: [
        { type: "p", text: "First, the experiments. They test a name or origin signal on an otherwise Dutch profile; the European test used CVs with Dutch education written in Dutch [5]. No Dutch study isolates a foreign degree, foreign work experience, a language level or a permit. They measure a positive response, not an offer, and an average over employers, not what a particular employer will do. Designs (written, telephone, walk-in, CV database), years (2008 to 2019) and job levels differ: the Panteia tests are mbo only, the SCP temp agency study is lower and mid-level, and only the SCP 2010 study separates hbo and wo. The no-difference result for online first-stage interest at temp agencies shows that the channel can matter [8]." },
        { type: "p", text: "Second, the register tables. CBS tables have no cross of education level, origin and unemployment rate. The hbo and wo data by origin are participation rates, not unemployment, and continent aggregates for them are computed by odds from country counts with a hand mapping, accurate to about one percentage point [13]. The data on staying distinguish international students but not the route by which they came or the permit they hold, and deregistration from the population register is a proxy for leaving the country [14]. Job search duration has no origin dimension [16]." },
        { type: "p", text: "Third, what odds does. It pools a migration background into a single factor, even though the region results run from about 0.67 to 0.83 [2]. It applies a ratio measured at one point in time to a base rate measured by vendors elsewhere, uses a non-Dutch audit study for foreign experience and a result from 2008 for the high bound. The multipliers are applied to the base as independent factors, which they are probably not, and the overlap rule is a simplification, not an estimate of the joint effect [5]. Intervals around the ratios are not held." },
        { type: "p", text: "Fourth, verification. The group-by-group ratios for the 2015 Panteia test, and several rows of a review table in the Dutch article (studies from 2015 and 2017), were not checked against the primary reports and are not used [2]. The 2019 Inspectie SZW pilot is reported without a sample size on the government page, and a news figure of 467 agencies was not verified [11]. The study-abroad article was read only through its abstract [6]. No Dutch correspondence test on refugees was found. None of these gaps changes the direction of the evidence, but each limits how far a reader should lean on a number." },
      ]
    },
    {
      heading: "What this means for odds",
      blocks: [
        { type: "p", text: "For the product, four principles follow from the evidence. The first is that a non-native profile receives a line in the derivation, showing the study, the year and the sample size, and carries the label experimental evidence. It is never shown as a verdict, and it is always combined with the other lines so that the final figure is a range [5]." },
        { type: "p", text: "The second is that the range carries the disagreement between sources. The low bound uses the pooled 0.76 and, when applicable, the foreign experience effect as well; the high bound uses the graduate-level 0.93 and never both effects. The Dutch experiments show that a real gap existed, not how large it is for a graduate today, and odds says so by printing a range. The third is that the register data are shown as outcomes of earlier cohorts, with their definitions and their limits, and are never multiplied into the estimate. The fourth is that the evidence is meant to improve: once enough real Dutch outcomes are logged in a cell (at least 30), a measured rate replaces the proxy for everyone in that cell [5]." },
        { type: "p", text: "An effect found on average does not tell anyone what a particular employer will do, so the estimate describes the market and not the person. The gap was larger in customer-facing roles in the SCP data, so the nature of a role may matter [3]. A referral changes the odds in general: Ashby reports that 52% of referred candidates passed the screen against 35% overall, and odds applies that factor only when a profile has a connection at the employer, from pooled software data rather than a Dutch experiment [17]. This report is not legal advice; questions about discrimination in employment belong with the official government sources." }
      ]
    }
  ],
  references: [
    "Thijssen, L., Coenders, M. and Lancee, B. (2021). Article on ethnic discrimination in the Dutch labour market using the Dutch arm of the GEMM correspondence test (JIMI). Netherlands, 4,211 applications, 2016 to 2018; predicted positive response for native names, migration background, Western and non-Western minorities.",
    "Thijssen, L., Coenders, M. and Lancee, B. (2019). Dutch arm of the GEMM correspondence test. Mens & Maatschappij 94(2). Netherlands, 4,211 applications, ten occupations at mbo and hbo level, 35 origin groups, July 2016 to April 2018.",
    "Andriessen, I., Nievers, E., Faulk, L. and Dagevos, J. (2010). Liever Mark dan Mohammed? Sociaal en Cultureel Planbureau (SCP), Netherlands. Written and telephone tests, 1,409 tests (1,342 valid), May to December 2008.",
    "Statistics Netherlands (CBS) (2026). Arbeidsdeelname; herkomst. CBS StatLine table 85456NED, annual values 2013 to 2025. Retrieved 29 September 2026 (CC BY 4.0).",
    "odds research notes (2026). How the interview rate is computed: base rate range, adjustments from field experiments, evidence tiers and the overlap rule. Internal method note, September 2026.",
    "Field experiment on study abroad among economics master's graduates, Belgium, Netherlands and Spain (2026). Taylor & Francis journal article (doi 10.1080/21568235.2026.2683040). 2,100 applications to 700 real starter vacancies, February to June 2023; read from the abstract.",
    "Panteia for the Ministry of Social Affairs and Employment (SZW) (2019). Herhaling virtuele praktijktests arbeidsmarktdiscriminatie. Netherlands, online CV databases, 707 CVs placed and 638 analysed, six mbo occupations, 2018 to 2019; also reports the 2015 results.",
    "Andriessen, I., Nievers, E. and Dagevos, J. (2012). Op achterstand (Discriminatiemonitor 2012). Sociaal en Cultureel Planbureau (SCP), Netherlands. Temp agencies in the Randstad, 460 valid walk-in visits by 20 actors and 263 online applications, April to December 2011.",
    "Blommaert, L., Coenders, M. and van Tubergen, F. (2014). Discrimination of Arabic-named applicants in the Netherlands: an internet-based field experiment examining different phases in online recruitment procedures. Social Forces 92(3). 636 fictitious CVs on two online CV databases, 2011.",
    "Panteia for the Ministry of Social Affairs and Employment (SZW) (2015). Discriminatie in de wervings- en selectiefase. Netherlands, virtual practice tests, 1,742 fictitious CVs (1,346 in the origin analysis), mbo-level profiles; figures as reported in Panteia (2019).",
    "Inspectie SZW (2019). Mystery-call pilot on temp agencies with a discriminatory client request, as reported by Rijksoverheid, news item of 11 July 2019.",
    "Lancee, B. et al. (2021). Ethnic discrimination in hiring: comparing groups across contexts. Results from a cross-national field experiment. Journal of Ethnic and Migration Studies, special issue. 19,181 applications, of which 4,463 in the Netherlands, 30 July 2016 to 1 June 2018.",
    "Statistics Netherlands (CBS) (2026). Arbeidsdeelname; herkomstlanden gedetailleerd. CBS StatLine table 84729NED, annual values 2021 to 2024. Retrieved 29 September 2026 (CC BY 4.0).",
    "Statistics Netherlands (CBS) (2026). Uitstromers hoger onderwijs; arbeidsmarktpositie na verlaten onderwijs. CBS StatLine table 85776NED, cohorts 2006/07 to 2023/24, positions up to ten years after leaving. Retrieved 29 September 2026 (CC BY 4.0).",
    "Statistics Netherlands (CBS) (2026). Arbeidsdeelname; onderwijsniveau. CBS StatLine table 85266NED, annual values 2013 to 2026, ages 15 to 75. Retrieved 29 September 2026 (CC BY 4.0).",
    "Statistics Netherlands (CBS) (2026). Werkloze beroepsbevolking; werkloosheidsduur en persoonskenmerken. CBS StatLine table 85312NED, annual values 2013 to 2026. Retrieved 29 September 2026 (CC BY 4.0).",
    "Ashby (2026). Talent Trends report, recruiting operations benchmarks. 54 million applications globally; 180,000 jobs in EMEA scale-ups; screen pass rate 35%, referral screen pass rate 52%, offer acceptance 81%, 170 applications per hire for business roles.",
    "SmartRecruiters (2025). Recruitment Benchmarks 2025. 89 million applications in 95 countries; applicants interviewed 3.9% and offered 1.2% globally, 5.4% interviewed in Germany.",
    "Mathematica. Do Employers Value Return Migrants? An experiment on the returns to foreign work experience. Audit study, more than 8,000 fictitious resumes, multiplier 0.88 for experience outside the local market; not run in the Netherlands.",
    "ResumeGo (2020). Cover letter research. United States, vendor test of 7,287 applications: callback 16.4% with a tailored cover letter, 12.5% with a generic one, 10.7% with none.",
    "UWV (2025). Werkgeversonderzoek 2025. Netherlands, 3,551 employers; hard-to-fill vacancies 45% overall, 44% in finance, 47% in ICT.",
    "odds research notes (2026). Review of Dutch hiring-discrimination field experiments, compiled 29 September 2026.",
    "Nuffic (2025). Stay rate of international graduates. Share of international graduates still in the Netherlands after five years: 25.3%.",
    "odds research notes (2026). Worked example of the interview range for an indirect tax accountant posting (non-EU profile, internship, non-EU experience, tailored application), September 2026."
  ]
}

export default report
