import type { Report } from "../types"

const report: Report = {
  slug: "reading-postings-and-limits",
  order: 8,
  title: "Reading postings with fixed rules, and what the estimate cannot tell you",
  subtitle: "How odds collects and reads job postings, what it leaves blank, and an honest account of the limits of every number.",
  category: "Method",
  minutes: 31,
  headline: { figure: "13,484", line: "postings read by written rules, collected 29 and 30 September 2026" },
  feeds: "How jobs are read",
  art: "lens",
  abstract: "Every estimate that odds shows about a job, whether interview chance, pay, net pay or permit fit, starts with a job posting that a set of written rules has read. This report describes how a pool of 13,484 postings, collected on 29 and 30 September 2026 from five routes, is read for pay, years of experience asked, degree, Dutch and named tools and skills; what is left blank when a rule finds nothing; and how the age of a posting is labelled. It then counts where the rules go wrong: 375 of the 1,116 postings flagged for Dutch carry no stronger word than \"speak\", a programming language shares its spelling with a Dutch word, and a degree rule reads \"Scrum Master\" as a master's. The second half explains why the interview estimate stays a proxy range of about 2% to 7%: there is no measured Dutch base, the funnel figures come from hiring-software vendors, the field experiments used fictitious CVs, several effects overlap, and a salary spot check agrees with the register only after an age adjustment. It closes with the plan to replace borrowed numbers with logged outcomes, and with advice on reading a range.",
  findings: [
    "The pool holds 13,484 postings from five routes, 8,109 of them (60.1%) from public job boards and government sites, so a share such as the 8.3% flagged for Dutch describes this pool and not the Dutch market [1, 2].",
    "Pay is stated in 6,708 postings (49.7%), years of experience in 5,640 (41.8%) and a degree level in 8,450 (62.7%), and whatever a rule does not find is left blank and never filled with a typical value [1, 3].",
    "The age of a posting is unknown for 4,933 postings, 565 are labelled only as listed 30 or more days, and freshness is measured against a Dutch median time to hire of 44.5 days [1, 4].",
    "The base chance of an interview is 2.4% to 5.4% per application, taken from hiring-software funnels in EMEA scale-ups and Germany and not from any Dutch measurement [5, 6].",
    "Dutch field experiments with fictitious CVs put the origin effect at 0.76 overall (46% to 35% callbacks, 4,211 applications) and 0.93 for hbo/wo-level jobs (46% to 43%, 1,342 valid tests), and the studies disagree about whether the gap narrows for graduate jobs [7, 8].",
    "In a spot check of 14 job titles, Glassdoor pay was below the CBS median for all 14 (ratios 0.47 to 0.97) and at or above 0.98 of it after CBS pay was adjusted to an assumed age band [9, 10].",
  ],
  sections: [
    {
      heading: "Introduction",
      blocks: [
        { type: "p", text: "A job card in odds shows an estimate of the chance of an interview, a pay figure, net pay after tax and whether the job clears a permit threshold. Each of these rests on something that happens before any calculation about the reader: a written rule reads the text of a job posting and decides what it asks for. If the rule finds \"3 years\" the card says three years. If it finds the word Dutch next to the word required, the card says Dutch is needed. The estimate about a person can only be as sound as that reading, and the reading is easy to overlook because it happens quietly, thousands of times, before anything appears on a screen." },
        { type: "p", text: "This report has two halves. The first describes how odds collects postings and reads them: where they come from, which facts are pulled out and by which rules, how old postings are labelled, and where the rules go wrong, with counts taken from the pool itself. The second describes the limits of the estimate built on top: the missing Dutch base rate and the vendor funnels that stand in for it, what field experiments with fictitious CVs can and cannot show, overlapping effects, the strength of each piece of evidence, a pay spot check against Glassdoor, and the plan to replace borrowed numbers with outcomes that users log themselves [11, 12]." },
        { type: "p", text: "The report is long because the product makes a strong promise. Its design rules say that every figure carries its source and year, that an unavailable value is shown with a reason and never replaced by a substitute, and that probabilities are ranges with the derivation printed, never a single-point chance of getting a job [11, 13]. Such a promise is worth something only if the weak places are described as carefully as the strong ones." },
        { type: "p", text: "Six questions organise what follows. Where do the postings come from? Which facts are read, and how often does a posting yield each? Why fixed rules and not a language model's reading? How is age expressed, and what happens to a posting of unknown or long age? Where do the rules fail? And what can the interview estimate not tell the reader, and what will replace its borrowed inputs? {ref:fig-lens} suggests the stance taken throughout: a lens magnifies only what was put on the table, and the reader is told what is on the table." },
        { type: "p", text: "Terms are used in a specific way. To \"read\" a posting means to match its text against written patterns, and a \"flag\" is a yes or no fact such a pattern sets, for example that Dutch is asked for. The \"pool\" is the set of postings odds has collected, a sample and not the labour market. A \"range\" has a low and a high end with the evidence behind each. The counts come from running the rules on the pool, and single rules were checked on constructed postings [1, 14]." },
        { type: "art", id: "fig-lens", kind: "lens", caption: "A lens on a table. It stands for the reading rules: they can magnify only what a posting actually says, and everything outside the lens stays as unread as before." },
      ],
    },
    {
      heading: "Data and sources",
      blocks: [
        { type: "p", text: "The pool holds 13,484 postings located in the Netherlands, collected on 29 and 30 September 2026, with about 2,020 distinct employer names as written in the data. A posting keeps the address it came from where the source gave one, so a reader can open the original [1, 2]. The pool is a snapshot: odds has not yet run a daily re-crawl, so it cannot say when a posting was taken down, only how old it claims to be on the day it was read [15]." },
        { type: "p", text: "{ref:fig-routes} shows the five routes. The largest, 8,109 postings, is public job boards and government sites: Magnet.me (4,270), EURES (1,311), Werken voor Nederland (1,202), Gemeentebanen (627), AcademicTransfer (479) and Werken bij de overheid (220) [16]. Next come 2,051 postings from the recruiting systems smaller employers use (Recruitee 937, SmartRecruiters 692, Greenhouse 253, Teamtailor 84, Ashby 48, Lever 31, Personio 6); 1,636 from LinkedIn searches for entry-level titles, gathered through a third-party collection service [17]; 1,367 from large employers' career sites (Workday 1,258, SuccessFactors 100, Ashby 9); and 321 from employer job boards read directly (Greenhouse 238, Ashby 83) [18]." },
        {
        type: "bars",
        id: "fig-routes",
        caption: "Postings in the odds pool by collection route, 29 and 30 September 2026 (n = 13,484).",
        unit: "postings",
        items: [
          { label: "Public job boards and government sites", value: 8109 },
          { label: "Smaller employers' recruiting systems", value: 2051 },
          { label: "LinkedIn search results", value: 1636 },
          { label: "Large employers' career sites", value: 1367 },
          { label: "Employer job boards read directly", value: 321 },
        ],
        note: "Source: odds collected postings [1]. Sub-source counts are given in the text. Sum of the five routes: 13,484.",
      },
        { type: "p", text: "The LinkedIn searches used titles such as junior financial analyst, financial controller, junior accountant, graduate programme and several internship titles, each set to the Netherlands [17, 1]. Nothing in the pool came from Glassdoor, Indeed or Payscale; Glassdoor pages were read once, for the pay check described later, and are not displayed [9]." },
        { type: "p", text: "The pool is larger than the live listing shown on the site on any given day. The how-it-works page, for one, counts only postings not in the \"listed 30 or more days\" state described below; 13,484 minus 565 leaves 12,919 counted as still up (plain subtraction) [1, 2]. On a given day the listing can be smaller again, as postings age out or close. The figures in this report describe the whole pool, because that is what the rules were run on." },
        { type: "p", text: "What the pool is made of matters for every share quoted later. By route, 60.1% of postings come from public boards and government sites. By language, a word-count test on the first 1,200 characters classes 3,222 postings (23.9%) as English and the other 10,262 (76.1%) as mostly Dutch-language [2]. By the categories assigned from the title, 3,714 (27.5%) are finance or business, 1,724 (12.8%) tech and 8,046 (59.7%) other [1]. A statement such as \"8.3% ask for Dutch\" is therefore about a mostly public-sector, mostly Dutch-language pool, not a national rate." },
        { type: "p", text: "Datasheet practice gives a way to state this honestly. The Datasheets for Datasets proposal asks whether a dataset contains all possible instances or a sample, and how instances were selected [19]. Here the pool is a sample selected by the routes above, and jobs filled through contacts, recruiters or internal moves never appear in it: exact for the pool, biased for the market, in the words of the product notes [12]. Two sources are joined to each posting. The employer name is matched against the IND register of recognised sponsors, 12,984 organisations [20]; a match means the employer is recognised, not that it will sponsor this role [12]. The title is matched to a CBS occupation group so that a pay range can be shown [10]. Matching succeeds for 7,437 postings (55.2%), so for the other 44.8% no occupation pay range can be shown [1]." },
      ],
    },
    {
      heading: "Reading a posting: what is extracted and how",
      blocks: [
        { type: "p", text: "{ref:tbl-fields} shows how many postings in each route yield each fact. The key point is that percentages differ widely between routes for reasons unrelated to the rules, which are identical for every route. What differs is what each source publishes. The 321 postings read directly from employer boards carry no date at all (0.0% with known age) and almost never state pay (0.3%), while 98.6% of postings from smaller employers' systems carry a date and 66.3% of public-sector postings state pay [1, 3]." },
        {
        type: "table",
        id: "tbl-fields",
        caption: "Share of postings in each route from which a fact was read or flagged (percent of the route; all-pool counts in the last row).",
        head: ["Route", "Postings", "Years asked", "Degree named", "Pay stated", "Age known", "Dutch flagged"],
        rows: [
          ["Public boards and government", "8,109", "41.0%", "66.1%", "66.3%", "42.8%", "6.0%"],
          ["Smaller employers' systems", "2,051", "46.0%", "49.3%", "44.7%", "98.6%", "8.7%"],
          ["LinkedIn searches", "1,636", "32.3%", "73.5%", "8.8%", "95.8%", "12.7%"],
          ["Large employers' career sites", "1,367", "48.4%", "58.8%", "19.5%", "87.6%", "15.3%"],
          ["Employer boards read directly", "321", "56.1%", "22.7%", "0.3%", "0.0%", "11.2%"],
          ["All postings", "13,484", "41.8% (5,640)", "62.7% (8,450)", "49.7% (6,708)", "63.4% (8,551)", "8.3% (1,116)"],
        ],
        note: "Source: odds collected postings and reading rules [1, 3]. A blank means the rule found nothing, not that the posting asks for nothing. The percentages are odds' own tabulation of the pool.",
      },
        { type: "h3", text: "Years, degree and Dutch" },
        { type: "p", text: "The years rule looks for a number from 1 to 15 followed by years, yrs or the Dutch jaar, optionally with a plus sign or a range such as \"3-5 years\". For a range it keeps the first number; if the text names several numbers, the smallest wins [3]. The aim is that \"3 years\" in one line and \"10 years of company history\" in another is not read as asking for ten. Among the 5,640 postings with a number, the commonest values are 5 years (1,255 postings), 3 (1,203), 1 (1,030) and 2 (913) [1]. In 486 of them (8.6%) the text contains more than one distinct number, so the choice of the smallest matters." },
        { type: "p", text: "The degree rule checks doctorate words first, then master's words (master, MSc, MBA), then bachelor's words (bachelor, BSc, hbo, wo), and reports the highest found, so a posting mentioning both a bachelor's and a master's reads as a master's [3]. In the pool 6,337 postings read as bachelor, 1,709 as master, 404 as doctorate and 5,034 name no degree [1]. Hbo is the applied-sciences level and wo the research-university level." },
        { type: "p", text: "The Dutch rule finds the word Dutch or Nederlands and then looks 80 characters either side for a trigger word: required, fluent, proficient, native, must, mandatory, essential, necessary, speak, or the Dutch vereist and verplicht [3]. It flags 1,116 postings (8.3%), while 4,677 mention the word at all. Visa words such as visa, sponsorship or \"highly skilled migrant\" mark a mention in 504 postings (3.7%), and junior, graduate, trainee or intern in the title marks a junior title in 1,573 (11.7%) [3, 1]." },
        { type: "h3", text: "Pay" },
        { type: "p", text: "Pay is taken as the employer wrote it. Of the 6,708 postings that state pay, 5,380 come from public boards and government sites, where pay is often a salary scale with a range [1]. odds does not convert or clean these strings, and at least one is in Singapore dollars. When a posting states pay, odds shows it labelled as stated by the employer. When it does not, odds shows the CBS 2024 range for the matched occupation group, labelled typical for the job and never as this employer's offer, and where neither exists it says there is no pay figure [11, 10]." },
        { type: "p", text: "Stated pay should remain a minority for a legal reason too. The Dutch bill implementing the EU pay transparency directive is not in force as of 29 September 2026, the target date is 1 January 2027, and the bill requires pay or its range to be given before the interview, not in the vacancy text [21]." },
        { type: "h3", text: "Tools versus skills" },
        { type: "p", text: "odds keeps a written dictionary of 142 things a posting can name: 61 tools (software, systems and programming languages, such as Excel, SQL, SAP or Python) and 81 skills (things you know how to do, such as IFRS, forecasting, audit or stakeholder management) [3]. Each pattern is written to match the thing itself and not a common word near it. Excel does not count in \"excel in a fast-paced team\", React does not count in \"react quickly\", and Workday counts only when a Workday product word follows, since otherwise it is usually the employer's name." },
        { type: "h3", text: "Finding the part that matters" },
        { type: "p", text: "A posting mixes what the company does, what the holder will do, what is offered and what is asked, and only the last should count as a requirement. odds finds it by headings in English and Dutch. A line under 70 characters ending in a colon, or under 40 characters, is a heading. Headings such as Requirements, What you'll bring, Wat breng je mee or Jouw profiel open the section; What we offer, Responsibilities, Wat bieden wij or Over ons close it. Inside, lines of 13 to 240 characters are kept with bullets stripped, and reading stops after 14 lines. With no such section, tools and skills are read from the whole text, which finds more stray words [3]." },
        { type: "p", text: "A constructed posting shows the result. It had an \"About us\" paragraph mentioning 10 years in payments, a \"What you'll bring:\" list with \"3-5 years of experience in financial reporting, with strong Excel and SQL skills\", \"A bachelor's or master's degree in finance\", \"Fluent English is required; Dutch is a plus\" and \"You react quickly and excel in a fast-paced team\", and a \"What we offer:\" section. The rules kept four lines, found Excel, SQL and financial reporting, and correctly ignored \"react\" and \"excel\" in the last line. They read the years as 3 (the smaller number wins), the degree as a master's, and Dutch as required, because \"required\" lies within 80 characters of \"Dutch\" [14]. Two of these are errors, which the next section counts." },
      ],
    },
    {
      heading: "Why fixed rules, and what they cost",
      blocks: [
        { type: "p", text: "A language model would read postings more flexibly: it would catch \"a couple of years in a similar role\", which the rules cannot see. odds chose written rules anyway, for reasons drawn from its design principles and not from a measured contest. The product requirements say odds counts and never rates, and that every figure carries its source [11]. A rule can point at the exact characters that produced a fact; a model's guess cannot." },
        { type: "p", text: "The first reason is that a reading must survive being checked. In a live experiment with a commercial chatbot, participants shown zero, one or five citations trusted an answer more when citations were present, even random ones, and significantly less when they checked them [22]. Trust that rises on sight and falls on checking is the wrong shape for a product whose users are making decisions about their working lives, and those most likely to check care most. A reading traced to a line of the posting does not have that problem." },
        { type: "p", text: "Second, rules are repeatable: the same posting gives the same answer today and next month, so counts stay comparable. Third, a rule cannot invent a requirement. Fourth, disclosure: a study of 3,861 people found that labelling content as AI-generated reduced its perceived accuracy [23], so if a model were ever used, what it did and what the data did would have to be stated separately." },
        { type: "p", text: "The prior art review points the same way: several products print a percentage with no method behind it, and only one of 28 match-score products examined publishes component weights [24]. Rules are not more accurate simply by being rules; the difference is that odds prints the line beside each reading, so the reader becomes the checker." },
        { type: "p", text: "None of this is a measured claim of accuracy. The research files contain no comparison of the rules with a language model on the same postings, and no score of the rules against hand-labelled postings. The counts here say how often a rule fired, which is exact for the pool, not how often it was right. {ref:tbl-failures} counts the failures that could be found." },
        {
        type: "table",
        id: "tbl-failures",
        caption: "Known failure modes of the reading rules, with counts from the pool where the pool allows one.",
        head: ["Rule", "What goes wrong", "How often in the pool"],
        rows: [
          ["Dutch flag", "The word \"speak\" is enough to trigger the flag; wording such as \"not required\" or \"is a plus\" sits next to a trigger word", "375 of the 1,116 flagged postings contain no trigger word other than \"speak\"; 110 of the 1,116 also have wording such as \"is a plus\", \"an asset\" or \"preferred\" shortly after the word Dutch"],
          ["Tool: Rust", "The programming language shares its spelling with the Dutch word for calm", "317 postings carry the Rust flag; 161 of them contain a Dutch phrase such as \"rust te\" or \"voor rust\" and no programming word"],
          ["Degree", "\"Scrum Master\" matches master; \"bachelor or master\" reads as master", "54 master-flagged postings mention Scrum Master, 46 of them with no other master word; 977 of the 1,709 also name a bachelor word"],
          ["Years", "Smallest number wins, so \"founded 2 years ago\" can lower a real ask of 5", "486 postings contain more than one distinct number; in the constructed test, 2 was read instead of 5"],
          ["Requirement lines", "Leading digits are stripped with the bullet, so a line starting \"3-5 years\" loses its years; lines of 12 characters or fewer are dropped", "Not counted in the pool; shown in the constructed test"],
          ["Plain wording", "\"Drie jaar\", \"a couple of years\" and \"fluent in both languages\" have no rule", "Not counted; years, degree or Dutch stay blank or unflagged"],
        ],
        note: "Source: odds collected postings and reading rules, with counts by odds research notes [1, 3, 14]. The Rust phrase search is a rough check, not a labelled test.",
      },
      ],
    },
    {
      heading: "Posting age: five states and the 30 plus treatment",
      blocks: [
        { type: "p", text: "Boards show age in different ways: an exact date, a phrase such as \"posted 5 days ago\" or \"30+ days ago\", or nothing. odds turns what it finds into a state, using the Dutch median time to hire, 44.5 days, as the reference point. That figure comes from the Intelligence Group's Recruitment Kengetallen 2026 (AGO data of 4,000 or more per quarter), and the product requirements adopt it as the yardstick for a normal time to fill a role [4, 11]. A posting is fresh under 7 days, active from 7 to 45 days, and aging beyond 45. For ages read from \"days ago\" text the aging band ends at 60 days, and for exact dates at 90, after which the posting is old. \"30+ days ago\" has its own state, and no age at all is unknown [2]." },
        { type: "p", text: "{ref:fig-fresh} shows the division. The largest group, 4,933 postings, has unknown age, mostly from public boards, where 4,490 of 8,109 postings (55.4%) show no date. Then come 3,893 active, 1,622 fresh, 1,559 old on an exact date, 912 aging and 565 listed 30 or more days [1]. Old postings are uneven: of the 2,051 from smaller employers' systems, 1,080 (52.7%) are over 90 days old, which suggests some leave openings up a long time, but the pool cannot say whether they are still recruiting." },
        {
        type: "bars",
        id: "fig-fresh",
        caption: "Postings in the pool by freshness state (n = 13,484). The six groups add up to the whole pool.",
        unit: "postings",
        items: [
          { label: "Age not known", value: 4933 },
          { label: "Active (7 to 45 days)", value: 3893 },
          { label: "Fresh (under 7 days)", value: 1622 },
          { label: "Old (over 90 days, exact date)", value: 1559 },
          { label: "Aging (over 45 days)", value: 912 },
          { label: "Listed 30 or more days, exact age unknown", value: 565 },
        ],
        note: "Source: odds collected postings and build rules [1, 2]. Aging ends at 60 days for ages read from text and at 90 days for exact dates.",
      },
        { type: "p", text: "The \"30 or more days\" state exists because some career sites say only that. All 565 such postings come from large employers' career sites, 41.3% of that route's 1,367 [1]. odds cannot tell whether one is 31 days old or 300, so it shows \"30+ days ago\", never calls it new, leaves it out of the count of postings still up, and lets the reader decide. A posting counts as new only if it went up within a day [2]." },
        { type: "p", text: "Two judgement calls sit inside these labels. The first is an inconsistency: the design documents describe the aging band as 45 to 60 days, while the pool build applies 90 days to exact dates, so the same age can be labelled differently depending on how a board states it [11, 2]. The second is what an old posting means. It may be evergreen, already filled, or a genuinely hard role: a UWV survey of 3,551 employers found 45% of vacancies reported as hard to fill, 44% in finance and 47% in ICT [25]. The survey does not separate the cases and neither does the pool. The 44.5 days is a median time to hire, not a measure of how long postings stay online, so it helps compare postings but does not prove one is dead." },
        { type: "p", text: "Where ages are known they can be summarised per employer; the pool's summary gives a median age of open postings of 13 days at Philips and ASML, 15 at ING and 25 at NN Group [1]. Turning these into \"how long this employer takes to fill a role\" needs first-seen and last-seen dates from repeated collection, which a snapshot lacks [15]." },
      ],
    },
    {
      heading: "The interview estimate: a borrowed base, narrow experiments, overlapping effects",
      blocks: [
        { type: "p", text: "The second half turns to the estimate built on the readings. It is the chance of an interview for this profile applying to this posting, not the chance of getting the job. It has two kinds of evidence that the product tries never to blur: a base rate, the share of applicants who got an interview in some measured group, and adjustments, each the effect of one trait measured in a field experiment in which two otherwise identical CVs were sent to real vacancies [12]." },
        { type: "h3", text: "A base rate that nobody has measured for the Netherlands" },
        { type: "p", text: "No source in the files publishes how many applicants in the Netherlands get an interview. The base comes from two hiring-software companies. SmartRecruiters reports for 2025 that across 89 million applications in 95 countries 3.9% of applicants were interviewed and 1.2% offered, or 3.25 interviews per offer, and that in Germany 5.4% were interviewed [5]. Ashby reports for 2026 170 applications per hire in business roles in EMEA scale-ups (180,000 jobs) and 81% of offers accepted [6]. Chaining them: 1 hire per 170 applications is 0.59%; divided by 0.81 that is 0.73% offers; times 3.25 gives about 2.4% interviews per application (plain arithmetic). The German figure, 5.4%, is 2.3 times higher for what looks like the same question [12]." },
        { type: "p", text: "The causes of the gap cannot be resolved from the files. An interview means a phone screen in one data set and a scheduled round in the other, the customer groups differ, both are companies that buy recruiting software and so not a random sample of Dutch employers, and Germany is not the Netherlands. A third vendor, Employ, reports interview to offer rates of 72.2% in enterprise, 16.6% in mid-market and 7% in small business, a different definition again, kept only as a label for a later stage [26]. The base is therefore a range of 2.4% to 5.4%, printed with both derivations; any single figure would be a choice. {ref:fig-ranges} sets it beside the other figures in the files." },
        {
        type: "ranges",
        id: "fig-ranges",
        caption: "Figures for the chance of an interview per application that appear in the research files, as low and high ends.",
        unit: "% of applications",
        max: 12,
        items: [
          { label: "Base range used by odds (Ashby chain to Germany)", low: 2.4, high: 5.4 },
          { label: "Ashby 2026, applications to interview, global customers", low: 3.6, high: 4.7 },
          { label: "Reddit self-reports, interquartile range (20 rows)", low: 0, high: 10 },
          { label: "Worked example as shown by odds (low to high end)", low: 1.8, high: 7.4 },
        ],
        note: "Sources: SmartRecruiters 2025, Ashby 2026, Reddit self-reports, odds worked example [5, 6, 27, 12]. The Reddit median is 1.5% and is not drawn. Figures are not measured for the Netherlands except the Reddit rows, which are self-selected.",
      },
        { type: "p", text: "Two checks point the same way. Ashby's direct measure across global customers (109 million applications, January 2021 to March 2026) puts 3.6% to 4.7% of applications at an interview, with 291 applications per hire [6]. And a harvest of self-reports by job seekers in the Netherlands on Reddit gave 20 high-confidence rows with at least 10 applications each, with a median of 90 applications and 2 interviews, or 1.5% per application (interquartile range 0% to 10%) [27]. That sample is tiny and survivor-biased, since people write when something is not working, so it is used only to check direction." },
        { type: "h3", text: "What fictitious-CV experiments can and cannot show" },
        { type: "p", text: "The adjustments come from field experiments, the best tool for isolating one trait. The Dutch arm of the GEMM project sent 4,211 applications in 2016 to 2018 across ten occupations at mbo and hbo level, and found callbacks of 46% for a native background against 35% for a migrant background, a ratio of 0.76 [7]. The SCP experiment, with 2008 data, ran 1,409 tests (1,342 valid) and found a smaller gap at hbo/wo level, 46% against 43% (0.93), against 40% and 32% at the lowest function level [8]. Other adjustments come from a Belgian internship experiment (1.126) [28], a non-Dutch audit study of work experience abroad (0.88, over 8,000 fictitious resumes) [29] and a United States vendor test of tailored cover letters (16.4% against 12.5%, 7,287 applications), counted only in the high end [30]. A study of study-abroad periods among economics graduates in Belgium, the Netherlands and Spain found no effect on invitations [31]." },
        { type: "p", text: "Each has limits the product cannot repair. They measure a first reaction, not a job. They describe a fictitious applicant: the Dutch experiments used CVs with Dutch education in Dutch, so they show a name and origin effect only, and an international graduate with a foreign degree and an English CV is a different applicant [12]. They are old or far away: the Dutch split by function level rests on 2008 data, the internship effect is Belgian, the foreign experience effect is not Dutch, and the cover letter result is a vendor's test. No Dutch test isolating a foreign degree or foreign work experience was found, so those factors have no Dutch number." },
        { type: "p", text: "The studies also disagree. On whether the origin gap shrinks for graduate jobs, the SCP study, the only one with a clean function-level split, finds a smaller gap at hbo/wo level, while the GEMM analysis by occupation finds no narrowing overall, only that for account managers Western and non-Western minorities are penalised equally [32, 8]. That is why the product shows a low and a high end. A finding of no effect is also easy to over-read: the study-abroad result covers master's economics starters in three countries and says nothing about a whole foreign degree [31]." },
        { type: "h3", text: "Effects that overlap" },
        { type: "p", text: "The origin effect and the foreign experience effect probably measure the same employer reaction seen from two sides, so multiplying both would count it twice. The low end multiplies them (0.76 times 0.88, about 0.67) and the high end uses only one; nobody has measured the overlap, so this is a judgement. A vendor factor enters only the high end, an experimental effect enters both, and logged Dutch outcomes will replace the base once a cell has 30 entries [12]." },
        { type: "p", text: "A worked example shows the arithmetic. For an Indirect Tax Accountant role at a payments company, for a non-EU applicant with an internship, non-EU work experience and a tailored application, the low end is 2.4% times 0.67 times 1.126, or 1.8%, and the high end 5.4% times 0.93 times 1.126 times 1.31, or 7.4%. The card shows \"about 2% to 7%, proxy estimate\". An earlier, tighter 4.5% to 6.2% was tighter only because it hid the disagreement between the two bases and the overlap [12]." },
        { type: "p", text: "Two quieter problems remain. First, how many of a posting's requirements the applicant meets probably decides more than anything, yet no calibrated coefficient exists, so it is shown as a fact and not multiplied. Matched-CV callbacks in the Dutch experiment (54% for software developers, 27% for account managers, 18% for administrative clerks) are about 3 to 22 times the 2.4% to 5.4% base, depending on which ends are compared (plain arithmetic), a bracket for the fit effect and not a coefficient [32, 12]. Second, the chance of at least one interview in N applications, 1 minus (1 minus p) to the power N, assumes independent draws, but one person sends the same CV with the same permit and Dutch level, so outcomes move together and the formula overstates. At the low end of the example, 1.8% over 20 applications gives about 30%, labelled an upper bound until logged outcomes supply the real distribution [12]." },
      ],
    },
    {
      heading: "Evidence tiers, the Glassdoor spot check and the move to logged outcomes",
      blocks: [
        { type: "p", text: "Every factor behind the estimate carries a tier, a word for how much weight the evidence deserves and where it is allowed to enter. {ref:tbl-tiers} lists the vocabulary as odds uses it." },
        {
        type: "table",
        id: "tbl-tiers",
        caption: "Evidence tiers used by odds and what each is allowed to do.",
        head: ["Tier", "What it means", "Where it enters the range"],
        rows: [
          ["Measured in the Netherlands", "odds' own log of Dutch outcomes", "Planned, not built yet: replaces the base entirely once a cell holds at least 30 entries"],
          ["Experimental effect", "A field experiment with matched CVs", "Both the low and the high end"],
          ["Benchmark proxy", "An aggregate from hiring software, not an experiment", "Used as a proxy; applied only when it applies to the person"],
          ["Vendor", "A company's own test", "High end only"],
          ["Messy", "Self-reports, such as Reddit posts", "Never displayed; checks direction only"],
          ["Dated", "An older source, such as CBS wage growth from 2013", "Shown with its date"],
          ["Current", "A recent source, such as CPB 2025", "Shown as is"],
        ],
        note: "Source: odds research notes on the interview estimate [12].",
      },
        { type: "p", text: "Alongside the tiers sits a confidence label for each statistic on screen. Gross pay by occupation from the CBS register is rated high, since it covers the whole employed population, with the caveat that an occupation group can be wide: accountants span juniors to partners [10, 12]. Net pay and thresholds are high because they follow the law. Sponsor status is high as a fact about the register, not as a promise about a role. Career paths from JobHop, 333,000 Flemish self-reported careers, are medium because they describe and do not personalise [33]. The interview rate and interview to offer rate are low, and the applicant count per posting is none [12]." },
        { type: "p", text: "The last label sits awkwardly beside the data: the LinkedIn route returned applicant-count text for 893 of 1,636 postings, and the job page shows it when it exists [1, 17]. The notes rate the statistic none because no legitimate source exposes it in general; the displayed text is the source's own, unchecked, missing for most postings and not used in the estimate." },
        { type: "p", text: "The pay-growth evidence shows the dated and current tiers side by side. CBS wage pairs for 2006 to 2011 show growth of 3.6% for stayers and 6.8% for an employer change [34], while CPB microdata for 2015 to 2022 show about one percentage point of extra hourly wage growth from switching in a tight market [35]. No Dutch source in the files gives switcher against stayer growth by year for 2019 to 2025, so the product shows the older spread with its date and the newer effect, nothing between." },
        { type: "h3", text: "The Glassdoor spot check" },
        { type: "p", text: "For pay, odds relies on the CBS register. Glassdoor publishes self-reported salaries with a count and confidence label, skewing junior and towards employers such as the Big 4 [12]. On 29 September 2026 odds compared Glassdoor.nl's pages for 14 job titles with CBS 2024 pay. Glassdoor's terms do not allow the pages to be shown, so the check is for calibration only, and a second pass on three titles was blocked [9]. {ref:tbl-gd} gives eight of the 14." },
        {
        type: "table",
        id: "tbl-gd",
        caption: "Glassdoor.nl pay against CBS 2024 pay for eight of 14 job titles. A ratio of 1.00 would mean the two agree.",
        head: ["Job title", "Glassdoor reports (n)", "Glassdoor against CBS median", "Against CBS median adjusted to an assumed age band"],
        rows: [
          ["Accountant", "288", "0.66", "0.98"],
          ["Financial analyst", "341", "0.75", "1.10"],
          ["Financial controller", "425", "0.92", "1.08"],
          ["Software engineer", "5,500", "0.97", "1.08"],
          ["Data analyst", "559", "0.85", "1.20"],
          ["Business analyst", "1,300", "0.93", "1.34"],
          ["Consultant", "3,900", "0.81", "1.17"],
          ["Junior accountant", "not recorded", "0.47", "1.00"],
        ],
        note: "Source: Glassdoor.nl salary pages read 29 September 2026; CBS 2024 pay by occupation; age factors from CBS 81431NED [9, 10, 36]. The age band is an assumption by odds for each title.",
      },
        { type: "p", text: "The setup decides what the comparison shows. Against the unadjusted CBS median, Glassdoor is lower for all 14 titles, with ratios from 0.47 to 0.97 and a median of 0.85, as expected if respondents are younger than the average employee in the register. So odds adjusted CBS pay to the age band each entry seems to refer to, using the ratio of mean hourly pay in that band to the sector total, for example 0.675 for finance workers aged 25 to 30 [36]. After that the ratios run from 0.98 to 1.34 with a median of about 1.1. Seven of 14 lie within 10% of 1.00, where the hand-off notes count eight, and all 14 are at or above 0.98, so the misses all go one way, with Glassdoor above the adjusted register pay [9, 15]. A wrong age assumption would produce that, and so would a wide occupation group or a different employer mix; the check cannot tell them apart." },
        { type: "p", text: "The notes summarise the check as \"within 1 to 2%\" for two titles and \"20 to 27% below\" for two others. The stored ratios do not reproduce that summary cleanly, so this report relies on the table. It is a spot check of a few titles on one day and cannot show that Glassdoor is reliable or unreliable in general; the register remains the primary source [12, 9]. Glassdoor also never publishes an interview rate per application: its percentages, such as the share who applied online, are shares among people who already got an interview, not a chance of getting through [12]." },
        { type: "h3", text: "The plan: logged outcomes replace borrowed numbers" },
        { type: "p", text: "The only ground truth is an outcome log. Each entry records the occupation, how well the profile fitted the posting (clears, one requirement missing, or below), employer size, permit status, Dutch level and the furthest stage reached. A cell is an occupation combined with a fit tier, and once a cell holds 30 entries odds shows a measured rate in place of the proxy. With 10 finance and tech occupations and 3 fit tiers there are 30 cells, so about 900 logged applications, or about 45 people at about 20 applications each [12]. The yardstick is calibration: UWV's Werkverkenner 2.0 model, which predicts a job within 12 months for benefit claimants, reports an AUC of 0.778 and a Brier score (how far predicted chances sat from what happened) of 0.191 on 53,079 people, and that Brier score is the bar the log is held to [37]." },
        { type: "p", text: "Two caveats apply. The log will come from people who chose to use odds and to log, so it is not a random sample either. And odds' own checks are imperfect: a validation on 29 September 2026 reports 58 checks, with 51 items matching the source files, 3 stored in a different format, 4 stated from memory and since sourced, and 1 unsourced (the employee pension share, which varies by collective agreement) [38]. Those groups add up to 59, not 58, so the record is approximate and should be corrected." },
      ],
    },
    {
      heading: "Discussion",
      blocks: [
        { type: "p", text: "Two kinds of uncertainty run through this report. The first is uncertainty in reading: a rule sets a flag wrongly or misses a plainly written fact. It is countable, testable against a hand-labelled sample, fixable by changing a pattern, and checkable by the user, who can open the posting and read the sentence behind the flag. The second is uncertainty in the base: nobody has measured how many applicants in the Netherlands reach an interview, the experiments describe fictitious applicants in other years and places, and the effects overlap by an unknown amount. The user cannot check this kind, and only collected outcomes can reduce it." },
        { type: "p", text: "Where sources differ, the differences have nameable reasons. Stated pay runs from 0.3% in one route to 66.3% in another because sources publish different fields, not because the rule changed. Two funnels differ by a factor of 2.3 because of how an interview is defined and who the customers are. Glassdoor sits below the register until the register is adjusted for age, then above it, because the age band is an assumption." },
        { type: "p", text: "The two halves are linked. The method notes say that checklist coverage, how many of the asked-for tools and skills the reader has, is shown as a fact and not multiplied into the percentage [12]. A misreading therefore shows up in the checklist and in filters such as Dutch-required, and does not directly move the range. That limits the damage but does not remove it: a reader who skips a job because of a wrong Dutch flag has made a real decision on a wrong reading. For international graduates a false alarm is costly, so the 375 flags resting on the word \"speak\" alone are arguably the most consequential number in the failure table. The composition matters too: where three quarters of postings are not classed as English, most are simply written in Dutch without asking for it, so a missing flag says little about the language a job needs." },
        { type: "p", text: "Finally, printing the reading beside its source line makes these problems visible. A rule firing on the wrong word is an error the reader can see and overrule in seconds; a model's silent misreading would look identical on screen. The cost is that the rules miss plain wording and the card says \"Not stated\" where a reader might expect an answer. The report takes that cost as acceptable for now on the reasoning of the design rules, not because the rules have been shown to beat an alternative [11, 22]." },
      ],
    },
    {
      heading: "Limitations",
      blocks: [
        { type: "p", text: "The limits fall into three groups: how postings were collected and read, how the estimate is built, and how the checks were done." },
        {
        type: "list",
        items: [
          "**The reading rules have not been scored for accuracy.** No hand-labelled sample exists. The failure counts are exact pattern matches or rough phrase searches, not error rates, and the Rust count rests on a crude search for four Dutch phrases and a list of programming words [1, 14].",
          "**The pool is a two-day snapshot and a sample.** It was collected on 29 and 30 September 2026, has not been re-crawled, leans to public-sector and student-oriented sources, is 76.1% not classed as English, and excludes jobs filled through contacts or recruiters [1, 15].",
          "**Occupation matching is coarse.** Titles are matched by ordered keyword patterns, 44.8% of the pool gets no match, and the pay range shown is the occupation group's, not the employer's [1, 10].",
          "**Pay strings and ages are the source's own.** Pay is kept as written, at least one in a foreign currency, and the age bands are a judgement whose 60-day and 90-day cut-offs differ; the pool cannot say whether an old posting is open [1, 2, 25].",
          "**The base is borrowed.** The vendor funnels cover customers of recruiting software in Germany and EMEA scale-ups, define an interview differently, and were not built to answer the product's question [5, 6, 26].",
          "**The experiments are old, foreign or narrow.** The Dutch ones show a name and origin effect for fictitious applicants with Dutch CVs, from 2008 and 2016 to 2018, and the records of the study-abroad experiment disagree on its size (2,100 applications to 700 vacancies in one, 2,100 vacancies in another) [8, 7, 31].",
          "**Overlap is unmeasured.** The 0.67 for two penalties is a judgement, and the independence assumption in the cumulative formula is known to be wrong [12].",
          "**Two checks are small.** The Reddit sample is tiny and self-selected, and the Glassdoor check covers 14 titles on one day with an assumed age band [27, 9].",
          "**The validation record is approximate** (59 items against 58 stated checks), and **the law may change**: pay transparency rules are not in force as of 29 September 2026 [38, 21].",
        ],
      },
        { type: "p", text: "Nothing here is a prediction about any individual. Every figure refers to the pool or a cited study, for the dates given." },
      ],
    },
    {
      heading: "What this means for odds",
      blocks: [
        { type: "p", text: "The findings turn into commitments already part of how odds behaves, and into work that follows. Each reading is shown next to the line it came from. When the rules find nothing, the card says \"Not stated\" and does not guess a typical value. A missing Dutch flag is not read as \"Dutch not needed\", because a rule can find evidence of a requirement but cannot prove its absence. Freshness is a state and a label, and \"30+ days ago\" is never shown as new. The interview estimate is labelled \"proxy estimate\" and printed with both ends of the base and each factor with its study, country and tier, never as a point [11, 12]." },
        { type: "p", text: "The work that follows has three parts. First, score the rules against a hand-labelled sample and report an error rate per rule. Second, fix the failures a pattern can fix: require a programming context for Rust, exclude Scrum Master from the degree rule, ignore a negated \"not required\", treat \"speak\" alone as weaker than \"required\", keep a leading number that is part of the ask, and read written numbers such as \"drie jaar\". Third, repeat the collection so that first-seen and last-seen dates replace the snapshot, and build the outcome log so that measured cells replace proxy ones at 30 entries. These follow from the failures counted here; they are not results." },
        { type: "h3", text: "How to use a range well" },
        { type: "p", text: "The product prints ranges and not hedge words, and the research it follows supports this. In five experiments, numeric uncertainty produced no significant difference in trust in the numbers compared with a control, while verbal hedges lowered it (effects on trust in the source of d = -0.03 numeric and d = -0.21 verbal) [39]. In a study of 51 gig drivers, range displays raised trust and reliance and adding hedging text reversed the gains [40]. The reader's part is to use the range well, and six habits follow." },
        {
        type: "list", ordered: true,
        items: [
          "**Read a range as a band and do not pick its middle.** The low end is what a cautious reading of the evidence allows, the high end what an optimistic but still sourced reading allows, and the truth for one person can lie outside both [12].",
          "**Compare postings with each other, not with 100%.** A posting with a higher range is probably a better bet than one with a lower range, other things equal. The ordering is more trustworthy than the level.",
          "**Open the original before ruling a job out.** If a card says Dutch or a master's is required, read the sentence behind the flag; if it looks wrong, it probably is. \"Not stated\" is a question for the employer, neither good nor bad news.",
          "**Treat \"30+ days ago\" and \"Date not shown\" as a prompt to check** the original before spending an evening on an application.",
          "**Do not multiply applications into certainty.** Many applications do not turn a low chance into a high one at the rate the formula suggests, because they are not independent draws.",
          "**Use the hard facts first, and trust your own log over the proxy.** Permit thresholds, register pay and sponsor status are rules and registers, not estimates. If your outcomes sit outside the range, that is information about you or the method, and worth recording.",
        ],
      },
        { type: "p", text: "That is what odds commits to: a range, a statement of what each part rests on, and a plain \"we do not know\" where that is so. The label \"proxy estimate\" is there on purpose; in the words of the research notes, it is the product's credibility, not a weakness [12]." },
      ],
    },
  ],
  references: [
    "odds research data (2026). Collected postings, 29 and 30 September 2026: 13,484 job postings located in the Netherlands from five routes, with the facts read from each by fixed rules. Counts computed by odds from the pool.",
    "odds research notes (2026). Collection and build procedure for the postings pool: routes, language test, occupation-group matching by title, and freshness states (fresh, active, aging, old, listed 30 or more days, unknown). State of 30 September 2026.",
    "odds (2026). Posting reading rules: a dictionary of 142 tools and skills, requirement-section detection in English and Dutch, and rules for years asked, degree, Dutch and visa words. Source code of the odds application, state of 30 September 2026.",
    "Intelligence Group (2026). Recruitment Kengetallen 2026: median time to hire in the Netherlands, 44.5 days. Sample: AGO data, more than 4,000 per quarter.",
    "SmartRecruiters (2025). Recruitment Benchmarks 2025. Global: 89 million applications across 95 countries, 3.9% of applicants interviewed and 1.2% offered; Germany: 5.4% interviewed.",
    "Ashby (2026). Talent Trends 2026. Business roles in EMEA scale-ups: 170 applications per hire (180,000 jobs); 54 million applications, 81% offer acceptance; 109 million applications (247,000 jobs, January 2021 to March 2026): 3.6% to 4.7% reach an interview, 291 applications per hire.",
    "Thijssen, Coenders and Lancee (2021). Dutch arm of the GEMM correspondence field experiment: 4,211 applications, 2016 to 2018, 35 origin groups, ten occupations at mbo and hbo level; callbacks 46% (native), 35% (migrant background), 33% (non-Western).",
    "Andriessen, Nievers, Faulk and Dagevos (2010). Liever Mark dan Mohammed? SCP. Field experiment with written and phone tests, May to December 2008: 1,409 tests, 1,342 valid; function levels low, middle and high (hbo/wo).",
    "odds research notes (2026). Glassdoor spot check, 29 September 2026: Glassdoor.nl salary pages for 14 job titles read in a browser and compared with CBS 2024 pay; calibration only, not displayed.",
    "Statistics Netherlands (CBS) (2025). StatLine table 86355NED, gross hourly wage by occupation group, P25, P50 and P75, 2013 to 2025 (7,465 observations). CC BY 4.0.",
    "odds (2026). Product requirements for the job finder: design rules (counting and not rating, every figure with its source and year, the user confirms their own data) and the freshness reference of 44.5 days. Internal document, 29 September 2026.",
    "odds research notes (2026). How the interview percentage is computed and what can be stood behind: base range, adjustments, tiers, confidence by statistic, and the plan for measured rates. 29 September 2026.",
    "odds (2026). Data schema: the only fields a screen may display; a field may be null only together with a stated reason (not captured, thin data, not exposed by source, not applicable). Internal document, 29 September 2026.",
    "odds research notes (2026). Worked example: the reading rules run on constructed postings, 30 September 2026.",
    "odds hand-off notes (2026). State of the prototype and data as of 29 September 2026, including the collection snapshot and the Glassdoor check summary.",
    "Public job boards and government recruitment sites read by odds (2026): Magnet.me, EURES, Werken voor Nederland, Gemeentebanen, AcademicTransfer and Werken bij de overheid. Collected 29 and 30 September 2026.",
    "Apify (2026). LinkedIn Jobs Scraper actor, a third-party collection service tested by odds. Returns title, company, location, posted date, applicant count text, experience and skills fields for a search query. Test run and notes, 2026.",
    "Public job-board endpoints of applicant-tracking systems (Greenhouse, Ashby, Lever, Recruitee, SmartRecruiters, Teamtailor, Personio) and the Workday and SuccessFactors career sites of large employers, read by odds (2026). Employer content; endpoints documented as public.",
    "Gebru et al. (2018, 2021). Datasheets for Datasets. arXiv 1803.09010. Seven sections: motivation, composition, collection process, preprocessing, uses, distribution, maintenance.",
    "IND (2026). Public register of recognised sponsors: 12,984 organisations with KvK numbers, pulled by odds on 29 September 2026.",
    "Tweede Kamer, Eerste Kamer and government sources (2026). Dutch transposition of Directive 2023/970 (pay transparency), bill 36 949; status as of 29 September 2026, compiled by odds.",
    "Ding et al. (2025). Citations and Trust in LLM Generated Responses. AAAI 2025, arXiv 2501.01303. Live question-answering experiment with zero, one or five citations, relevant and random.",
    "Altay et al. (2025). AI labeling reduces the perceived accuracy of online content but has limited broader effects. arXiv 2506.16202. Nationally representative sample, n = 3,861.",
    "odds research notes (2026). Prior art review, 29 September 2026: six research passes over about 250 pages on match-score products, government odds tools, career simulators, salary calculators, academic work and market simulations.",
    "UWV (2025). Werkgeversonderzoek 2025. Survey of 3,551 employers; 45% of vacancies reported hard to fill (finance 44%, ICT 47%).",
    "Employ (2026). 2026 hiring benchmarks (Jobvite, Lever and JazzHR customers, 6,640 customers). Interview to offer rate: 7% small business, 16.6% mid-market, 72.2% enterprise.",
    "Arctic Shift archive harvest of Reddit posts, 29 September 2026: 1,352 posts from 10 subreddits, 277 extracted rows (190 posts, 87 comments). Processed by odds. Self-reports.",
    "Baert et al. (2021). Field experiment with fictitious pairs of Belgian graduates sent to real openings; internship effect on interview invitation, ratio 1.126.",
    "Mathematica audit study, Do Employers Value Return Migrants? More than 8,000 fictitious resumes; callback multiplier 0.88 for work experience abroad. Not a Dutch study.",
    "ResumeGo (2020). Cover-letter test, 7,287 applications in the United States: callbacks 16.4% with a tailored letter, 12.5% generic, 10.7% none. Vendor test.",
    "Field experiment on study abroad among economics graduates in Belgium, the Netherlands and Spain (2026), Taylor and Francis. No effect of a study-abroad period on interview invitations. One record states 2,100 applications to 700 starter vacancies, another states 2,100 vacancies.",
    "Thijssen, Coenders and Lancee (2019). Mens & Maatschappij 94(2). Same 4,211 applications; positive response by occupation, all origins pooled: software developer 54%, account manager 27%, administrative clerk 18%.",
    "UGent and VDAB. JobHop, version 1: 333,000 Flemish career trajectories coded to ESCO with quarterly dates (Hugging Face, aida-ugent/JobHop). CC BY 4.0.",
    "Driessen and de Vries (2013). Verandering van werkgever, beroep en lonen. CBS Sociaaleconomische trends, December 2013. Annual wage pairs 2006 to 2011: stayers +3.6%, employer change +6.8%, employer and occupation change +9.7%.",
    "Scheer, Zulkarnain and Rademakers (2025). Arbeidsmarktkrapte en loongroei. CPB. CBS microdata on all employees, 2015 to 2022: about one percentage point extra hourly wage growth from switching in a tight market.",
    "Statistics Netherlands (CBS). StatLine table 81431NED, mean hourly wage by sector and age band; used by odds to build age factors (finance 25 to 30: 0.675, 30 to 35: 0.844; ICT 0.708 and 0.909).",
    "TNO (2018). Werkverkenner 2.0, report R10279, for UWV. Individual prediction of a job within 12 months for unemployment-benefit claimants, n = 53,079; AUC 0.778, Brier score 0.191.",
    "odds research notes (2026). Validation of quoted figures, 29 September 2026: 58 checks re-derived by script from the source files.",
    "van der Bles, van der Linden, Freeman and Spiegelhalter (2020). PNAS 117(14). Five experiments on communicating uncertainty with numeric ranges and verbal hedges.",
    "Chen, Wang, Sadeh and Fang (2025). Missing Pieces. FAccT 2025. Longitudinal in-situ study with 51 gig drivers, comparing mean-only, range and range-plus-hedging displays.",
  ],
}

export default report
