// Generated from app/build_data.py (SK): the skills a job text can name, with the pattern that finds each. Do not edit by hand.
export const SKILL_PATTERNS: Array<[string, RegExp]> = [
  ["ifrs", /\bifrs\b/i],
  ["us gaap", /\bgaap\b/i],
  ["excel", /\bexcel\b/i],
  ["sql", /\bsql\b/i],
  ["python", /\bpython\b/i],
  ["power bi", /\bpower ?bi\b/i],
  ["tableau", /\btableau\b/i],
  ["sap", /\bsap\b/i],
  ["oracle", /\boracle\b/i],
  ["netsuite", /\bnetsuite\b/i],
  ["financial modelling", /\bfinancial model(l)?ing\b/i],
  ["forecasting", /\bforecast/i],
  ["budgeting", /\bbudget/i],
  ["fp&a", /\bfp&a\b/i],
  ["audit", /\baudit/i],
  ["tax", /\btax\b/i],
  ["vat", /\bvat\b/i],
  ["treasury", /\btreasury\b/i],
  ["reconciliation", /\breconcil/i],
  ["consolidation", /\bconsolidat/i],
  ["cpa/aca/acca", /\b(cpa|aca|acca|cima)\b/i],
  ["cfa", /\bcfa\b/i],
  ["stakeholder management", /\bstakeholder/i],
  ["kyc/aml", /\b(kyc|aml)\b/i],
  ["risk management", /\brisk management\b/i],
  ["compliance", /\bcompliance\b/i],
  ["payments", /\bpayments?\b/i],
  ["java", /\bjava\b/i],
  ["kotlin", /\bkotlin\b/i],
  ["scala", /\bscala\b/i],
  ["javascript", /\bjavascript\b/i],
  ["typescript", /\btypescript\b/i],
  ["react", /\breact\b/i],
  ["node.js", /\bnode(\.js)?\b/i],
  ["aws", /\baws\b/i],
  ["gcp", /\bgcp\b|\bgoogle cloud\b/i],
  ["azure", /\bazure\b/i],
  ["kubernetes", /\bkubernetes\b|\bk8s\b/i],
  ["docker", /\bdocker\b/i],
  ["terraform", /\bterraform\b/i],
  ["spark", /\bspark\b/i],
  ["kafka", /\bkafka\b/i],
  ["airflow", /\bairflow\b/i],
  ["machine learning", /\bmachine learning\b/i],
  ["pytorch", /\bpytorch\b/i],
  ["tensorflow", /\btensorflow\b/i],
  ["ci/cd", /\bci\/cd\b/i],
  ["linux", /\blinux\b/i],
  ["rust", /\brust\b/i],
  ["c++", /\bc\+\+/i],
  ["c#", /\bc#/i],
  [".net", /\.net\b/i],
  ["php", /\bphp\b/i],
  ["swift", /\bswift\b/i],
  ["android", /\bandroid\b/i],
  ["ios", /\bios\b/i],
  ["snowflake", /\bsnowflake\b/i],
  ["dbt", /\bdbt\b/i],
  ["databricks", /\bdatabricks\b/i],
  ["product management", /\bproduct manag/i],
  ["agile/scrum", /\b(agile|scrum)\b/i],
  ["communication skills", /\bcommunication skills\b/i],
]
