/**
 * The one icon set: Phosphor, drawn on one grid at one stroke. Everything imports from here, under short names, so a library change
 * happens in this file only. Plain re-exports, so each chunk carries only the icons it uses.
 */
export {
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  SealCheck as BadgeCheckIcon,
  Bell as BellIcon,
  BookmarkSimple as BookmarkIcon,
  Buildings as BuildingsIcon,
  CalendarBlank as CalendarIcon,
  Camera as CameraIcon,
  Check as CheckIcon,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  CheckCircle as CircleCheckIcon,
  CaretCircleDown as CircleChevronDownIcon,
  Question as CircleHelpIcon,
  ArrowSquareOut as ExternalLinkIcon,
  Hash as HashIcon,
  Info as InfoIcon,
  LinkSimple as LinkIcon,
  CircleNotch as Loader2Icon,
  XCircle as OctagonXIcon,
  Plus as PlusIcon,
  CheckSquare as SquareCheckIcon,
  Warning as TriangleAlertIcon,
  TextT as TypeIcon,
  UploadSimple as UploadIcon,
  X as XIcon,
  Kanban as BoardIcon,
  Table as TableIcon,
  Rows as RowsIcon,
  PencilSimple as PencilIcon,
  Envelope as EnvelopeIcon,
  ListChecks as ListChecksIcon,
  Phone as PhoneIcon,
  UsersThree as PeopleIcon,
  Trash as TrashIcon,
  SortAscending as SortIcon,
  Eye as EyeIcon,
  EyeSlash as EyeSlashIcon,
  ChatCircleText as MessageIcon,
  MagnifyingGlass as SearchIcon,
  BatteryFull as BatteryIcon,
  BookOpen as BookOpenIcon,
  CellSignalFull as SignalIcon,
  Copy as CopyIcon,
  DotsThreeVertical as DotsThreeVerticalIcon,
  Export as ShareIcon,
  Lock as LockIcon,
  PlusSquare as PlusSquareIcon,
  Star as StarIcon,
  WifiHigh as WifiIcon,
} from "@phosphor-icons/react"
