import type { IconProps } from "@phosphor-icons/react"

/** Every icon's look, given once to IconContext in main.tsx: the bold weight, sized and coloured by the text around it. A prop on one icon still wins. */
export const ICON_STYLE: IconProps = { color: "currentColor", size: "1em", weight: "bold", mirrored: false }

/**
 * The one icon set: Phosphor, drawn on one grid at one stroke. Everything imports from here, under short names, so a library change
 * happens in this file only. Plain re-exports, so each chunk carries only the icons it uses.
 */
export {
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  SealCheck as BadgeCheckIcon,
  Bell as BellIcon,
  BookmarkSimple as BookmarkIcon,
  Buildings as BuildingsIcon,
  CalendarBlank as CalendarIcon,
  Camera as CameraIcon,
  Check as CheckIcon,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  CheckCircle as CircleCheckIcon,
  CaretCircleDown as CircleChevronDownIcon,
  Question as CircleHelpIcon,
  ArrowSquareOut as ExternalLinkIcon,
  Hash as HashIcon,
  Info as InfoIcon,
  LinkSimple as LinkIcon,
  CircleNotch as Loader2Icon,
  Minus as MinusIcon,
  XCircle as OctagonXIcon,
  Plus as PlusIcon,
  CheckSquare as SquareCheckIcon,
  Warning as TriangleAlertIcon,
  TextT as TypeIcon,
  UploadSimple as UploadIcon,
  User as UserRoundIcon,
  X as XIcon,
  ShieldCheck as ShieldCheckIcon,
  Kanban as BoardIcon,
  Table as TableIcon,
  Rows as RowsIcon,
  PencilSimple as PencilIcon,
  Envelope as EnvelopeIcon,
  ListChecks as ListChecksIcon,
  Phone as PhoneIcon,
  UsersThree as PeopleIcon,
  Trash as TrashIcon,
  SortAscending as SortIcon,
  Eye as EyeIcon,
  EyeSlash as EyeSlashIcon,
  ChatCircleText as MessageIcon,
  MagnifyingGlass as SearchIcon,
  BatteryFull as BatteryIcon,
  BookOpen as BookOpenIcon,
  CellSignalFull as SignalIcon,
  Copy as CopyIcon,
  DotsThree as DotsThreeIcon,
  DotsThreeVertical as DotsThreeVerticalIcon,
  Export as ShareIcon,
  Lock as LockIcon,
  PlusSquare as PlusSquareIcon,
  Star as StarIcon,
  WifiHigh as WifiIcon,
} from "@phosphor-icons/react"
