-- Keep the newly researched Philips internship and its employer avatar in source control.
update public.employer_facts
set logo = 'https://www.google.com/s2/favicons?domain=philips.com&sz=128'
where employer = 'philips';

insert into public.postings (
  id,
  employer,
  employer_display,
  ats,
  source,
  title,
  region,
  cat,
  url,
  dutch_required,
  visa_mention,
  junior_title,
  skills,
  pay_posted,
  seniority,
  body,
  posted_at,
  days_open,
  freshness_state,
  fetched_at,
  first_seen,
  last_seen,
  level,
  student_fit,
  english,
  restricted,
  screening,
  nationality_cond,
  title_clean,
  level_jev,
  level_conf,
  usable,
  workplace,
  job_type,
  requirements,
  enrollment,
  role_kind
)
values (
  'pphilips4475470399',
  'philips',
  'Philips',
  'linkedin',
  'linkedin_user',
  'Internship: Enabling Execution of 2030 Impact Ambitions',
  'Amsterdam, North Holland, Netherlands',
  'other',
  'https://www.linkedin.com/jobs/view/4475470399',
  false,
  false,
  true,
  array['Sustainability', 'Program delivery', 'Stakeholder engagement', 'Market research', 'Communications', 'Impact measurement'],
  '€400–€700 gross/month depending on educational level; possible housing compensation (€255–€300 net) and travel compensation up to €145 net',
  'Internship',
  'Support Philips Group Sustainability Office and its Impact Shaper Program. Tasks include program module delivery, participant and partner engagement, scheduling, action tracking, research in global health and sustainability, and preparing reports and presentations. English fluent. Must remain enrolled throughout the internship; final-year Bachelor or Master preferred. Start December 2026 or January 2027, 6–12 months (8+ preferred), 40 hours/week. Amsterdam primary location with weekly attendance at Eindhoven High Tech Campus; hybrid, at least 3 office days/week. Allowance €400–€700 gross/month based on education; housing and travel support subject to the listed conditions.',
  'Posted today',
  0,
  'fresh',
  '2026-10-08',
  '2026-10-08',
  '2026-10-08',
  'internship',
  true,
  true,
  false,
  false,
  false,
  'Internship: Enabling Execution of 2030 Impact Ambitions',
  'internship',
  0.98,
  0.9,
  'Hybrid',
  'internship',
  '{"pay":"€400–€700 gross/month by educational level; housing/travel support subject to conditions","hours":"40 hours/week; at least 3 office days/week","duration":"6–12 months; 8+ months preferred","language":"Fluent English","location":"Amsterdam, with weekly presence at Eindhoven High Tech Campus","education":"Final-year Bachelor or Master enrollment preferred; must remain enrolled throughout","start_date":"December 2026 or January 2027","workplace":"Hybrid"}'::jsonb,
  'required',
  'internship'
)
on conflict (id) do nothing;
